name = "msp-formal"
defaultTargets = ["Spec", "Sanity", "Proofs", "Artifacts", "Poseidon", "Primality"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Spec"

[[lean_lib]]
name = "Sanity"
globs = ["Sanity.+"]

[[lean_lib]]
name = "Proofs"
globs = ["Proofs.+"]

[[lean_lib]]
name = "Artifacts"
globs = ["Artifacts.+"]

[[lean_lib]]
name = "Poseidon"
globs = ["Poseidon.+"]

[[lean_lib]]
name = "Primality"
globs = ["Primality.+"]
