name = "msp-formal"
defaultTargets = ["Spec", "Sanity", "Proofs", "Artifacts", "Poseidon", "Primality", "Keccak", "Groth16", "Chain", "Mutations"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Spec"

[[lean_lib]]
name = "Sanity"
globs = ["Sanity.+"]

[[lean_lib]]
name = "Proofs"
globs = ["Proofs.+"]

[[lean_lib]]
name = "Artifacts"
globs = ["Artifacts.+"]

[[lean_lib]]
name = "Poseidon"
globs = ["Poseidon.+"]

[[lean_lib]]
name = "Primality"
globs = ["Primality.+"]

[[lean_lib]]
name = "Keccak"
globs = ["Keccak.+"]

[[lean_lib]]
name = "Groth16"
globs = ["Groth16.+"]

[[lean_lib]]
name = "Chain"
globs = ["Chain.+"]

[[lean_lib]]
name = "Mutations"
globs = ["Mutations.+"]
