#!/usr/bin/env python3
"""Generate typed Lean constants from pinned BN254 Poseidon reference data."""

import argparse
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
REPO_PINS = {
    "reference/poseidon_bn254.py": "22e6d2d7fd6984f387ee78215415489b996b77564859bb84a2967a3873cebde7",
    "reference/poseidon_bn254_constants.json": "aa4ff490f85bd66cdee8a926e24471d854f3e575d4fed354e0dbd550c77a59a2",
    "vectors/poseidon_bn254_vectors.json": "594b4c9441fe305f17b7706997802536ba55afced9ddd2813ad6d81da4c41a21",
    "tooling/export_vectors.js": "a7dfac04e66922c5ca30510edb56d2f1c84b52a9b46d3967c2b8085de7b5a977",
    "tooling/package-lock.json": "f64e99f822cfc5f09a047a79b7495432aef20a0f2b3d2f5b72d2d8f49b54b3db",
    "circuits/spend.circom": "97c24b754549fd576c1e3d1e70345eba5570143895a0a9cceeb7e22176cdf8af",
}
DEPENDENCY_PINS = {
    "circomlib/package.json": "79ed553f89b67cce3aff5ae30027ce1683cbe8b3f8e822be4354ec25b5d7808a",
    "circomlib/circuits/poseidon.circom": "2582464669b69827164bd08ee0337997e1957f2ab4f00cdd86d533ca5e9d9234",
    "circomlib/circuits/poseidon_constants.circom": "94c9e4b5ea891ab4d1ba626f1d719f8c661014d9b628f6096c803f75f39e3eee",
    "circomlibjs/package.json": "9c7e866ba70ada882020b7fd1d644a761149c50f59817f981d7bc347af1d30d7",
    "circomlibjs/src/poseidon_reference.js": "c7053f631e987b982c644ebfd505f83aa3baf220864926b17f393ee88ae56996",
    "circomlibjs/src/poseidon_constants.json": "354f31bbed9d9a8b884d8f2181e339cb425b6e3e4cc7240bd3dd22f0070f3f2c",
    "circomlibjs/src/poseidon_constants.js": "05158e0b3fab993603d5bb2eaffffc66bfa068f2188d0e75cd596afad263d7b0",
}
PRIME = 21888242871839275222246405745257275088548364400416034343698204186575808495617
ROUNDS = {3: 57, 4: 56, 11: 66}


def sha256(data):
    return hashlib.sha256(data).hexdigest()


def require(condition, message):
    if not condition:
        raise ValueError(message)


def verify_pins(base, pins):
    for relative, digest in pins.items():
        require(sha256((base / relative).read_bytes()) == digest,
                f"source changed: {base / relative}")


def decimal(value):
    return int(value, 16) if str(value).startswith("0x") else int(value)


def checked_constants(node_modules):
    verify_pins(ROOT, REPO_PINS)
    verify_pins(node_modules, DEPENDENCY_PINS)
    for package, version in (("circomlib", "2.0.5"), ("circomlibjs", "0.1.7")):
        require(json.loads((node_modules / package / "package.json").read_text())["version"] == version,
                f"wrong {package} version")
    source = json.loads((ROOT / "reference/poseidon_bn254_constants.json").read_text())
    upstream = json.loads((node_modules / "circomlibjs/src/poseidon_constants.json").read_text())
    require(int(source["prime"]) == PRIME, "wrong BN254 scalar modulus")
    for width, partial in ROUNDS.items():
        row = source[f"t{width}"]
        constants = list(map(int, row["C"]))
        matrix = [list(map(int, r)) for r in row["M"]]
        require(row["rounds_f"] == 8 and row["rounds_p"] == partial, "wrong round schedule")
        require(len(constants) == width * (8 + partial), "wrong round-constant count")
        require(len(matrix) == width and all(len(r) == width for r in matrix), "wrong matrix shape")
        require(all(0 <= x < PRIME for x in constants + sum(matrix, [])), "noncanonical constant")
        require(constants == list(map(decimal, upstream["C"][width - 2])), "reference C mismatch")
        require(matrix == [list(map(decimal, r)) for r in upstream["M"][width - 2]],
                "reference M mismatch")
    return source


def vector(values):
    return "⟨#[" + ", ".join(map(str, values)) + "], rfl⟩"


def render(source):
    out = ["import Poseidon.Permutation", "", "/-! Generated by `Poseidon/generate.py`; do not edit.",
           "Source: reference/poseidon_bn254_constants.json, SHA-256", REPO_PINS["reference/poseidon_bn254_constants.json"] + ".",
           "These are the ordinary reference constants, not the optimized sparse-round circuit constants. -/",
           "", "namespace MSP.Poseidon", ""]
    for width, partial in ROUNDS.items():
        row = source[f"t{width}"]
        rounds = [row["C"][i:i + width] for i in range(0, len(row["C"]), width)]
        out.extend([f"def params{width} : Parameters {width} where", "  fullRounds := 8",
                    f"  partialRounds := {partial}", "  constants := ⟨#["])
        out.append(",\n".join("    " + vector(r) for r in rounds))
        out.extend(["  ], rfl⟩", "  matrix := ⟨#["])
        out.append(",\n".join("    " + vector(r) for r in row["M"]))
        out.extend(["  ], rfl⟩", ""])
    out.extend(["end MSP.Poseidon", ""])
    return "\n".join(out)


def outputs(node_modules):
    constants = render(checked_constants(node_modules)).encode()
    manifest = {
        "format": 1,
        "scope": "Concrete ordinary Poseidon reference function; no optimized-circuit equivalence or security proof",
        "prime": str(PRIME),
        "parameters": {str(w): {"inputs": w - 1, "full_rounds": 8, "partial_rounds": rp,
                                "round_constants": w * (8 + rp), "matrix_entries": w * w}
                       for w, rp in ROUNDS.items()},
        "repository_sha256": REPO_PINS,
        "node_modules_sha256": DEPENDENCY_PINS,
        "generator_sha256": sha256(Path(__file__).read_bytes()),
        "generated_sha256": {"Constants.lean": sha256(constants)},
    }
    return {"Constants.lean": constants, "manifest.json": (json.dumps(manifest, indent=2) + "\n").encode()}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--node-modules", type=Path, default=ROOT / "tooling/node_modules")
    parser.add_argument("--check", action="store_true", help="check byte-for-byte regeneration without writing")
    args = parser.parse_args()
    for name, data in outputs(args.node_modules).items():
        path = HERE / name
        if args.check:
            require(path.read_bytes() == data, f"generated file differs: {path}")
        else:
            path.write_bytes(data)
    print("Poseidon constants, source pins and manifest match" if args.check else "Generated Poseidon constants and manifest")


if __name__ == "__main__":
    main()
