/- Generated by small_optimized_generate.py from the checked width-11 proof. -/
import Poseidon.Optimized3Certificates
import Poseidon.Hash

/-! Connect the indexed pre-S-box recurrence to the exact ordinary reference
permutation. Optimized schedule equivalence is proved separately. -/

namespace MSP.Poseidon.Optimized3

set_option maxRecDepth 16384
set_option maxHeartbeats 2000000

def run {α : Type} {n : ℕ} (step : Fin n → α → α) (start : α) (k : ℕ) : α :=
  ((List.finRange n).take k).foldl (fun s r => step r s) start

theorem run_zero {α : Type} {n : ℕ} (step : Fin n → α → α) (start : α) :
    run step start 0 = start := rfl

theorem run_succ {α : Type} {n k : ℕ} (step : Fin n → α → α) (start : α)
    (h : k < n) : run step start (k + 1) = step ⟨k, h⟩ (run step start k) := by
  unfold run
  rw [List.take_succ_eq_append_getElem (by simpa using h), List.foldl_append]
  simp

theorem run_full {α : Type} {n : ℕ} (step : Fin n → α → α) (start : α) :
    run step start n = (List.finRange n).foldl (fun s r => step r s) start := by
  unfold run
  rw [List.take_of_length_le (by simp [List.finRange])]

private theorem get_ofFn {n : ℕ} (f : Fin n → F) (i : Fin n) :
    (Vector.ofFn f).get i = f i := by
  simp [Vector.get]
  congr 1

theorem reference_round (r : Fin 65) (v : Vector F 3) :
    (fun i => (round params3 r v).get i) =
      mix M (fun i => if r.val < 4 ∨ 61 ≤ r.val ∨ i = 0 then
          (v.get i + referenceConstant r i) ^ 5 else v.get i + referenceConstant r i) := by
  funext i
  have hfr : params3.fullRounds = 8 := rfl
  have hpr : params3.partialRounds = 57 := rfl
  simp only [round, get_ofFn, hfr, hpr, Nat.reduceDiv, Nat.reduceAdd, mix, Matrix.vecMul, dotProduct,
    Fin.sum_univ_def, List.sum_eq_foldl, List.foldl_map]
  congr 1
  funext a j
  rw [matrix_reference, mul_comm]
  congr 2
  simp only [referenceConstant, Fin.ext_iff, Fin.val_zero]

def referenceStart (inputs : Fin 2 → F) : Vector F 3 :=
  Vector.ofFn fun i : Fin 3 =>
    if h : i.val = 0 then 0 else inputs ⟨i.val - 1, by omega⟩

def referenceState (inputs : Fin 2 → F) (k : ℕ) : Vector F 3 :=
  run (fun r : Fin 65 => round params3 r) (referenceStart inputs) k

def referencePre (inputs : Fin 2 → F) (r : Fin 65) : State :=
  fun i => (referenceState inputs r.val).get i + referenceConstant r i

theorem reference_initial (inputs : Fin 2 → F) :
    initialState inputs = referencePre inputs 0 := by
  funext i
  simp only [initialState, referencePre, referenceState, Fin.val_zero, run_zero, referenceStart,
    get_ofFn, initial_constant]

theorem reference_full_next (inputs : Fin 2 → F) (r : Fin 64)
    (h : r.val < 4 ∨ 61 ≤ r.val) :
    referencePre inputs ⟨r.val + 1, by omega⟩ =
      mix M (sbox (referencePre inputs ⟨r.val, by omega⟩)) +
        referenceConstant ⟨r.val + 1, by omega⟩ := by
  unfold referencePre referenceState
  rw [run_succ (fun r : Fin 65 => round params3 r) (referenceStart inputs) (show r.val < 65 by omega)]
  have hr := reference_round ⟨r.val, by omega⟩
    (run (fun r : Fin 65 => round params3 r) (referenceStart inputs) r.val)
  have hall : ∀ i : Fin 3, r.val < 4 ∨ 61 ≤ r.val ∨ i = 0 := by
    intro i
    rcases h with h | h
    · exact Or.inl h
    · exact Or.inr (Or.inl h)
  simp only [hall, ↓reduceIte] at hr
  funext i
  exact congrArg (· + referenceConstant ⟨r.val + 1, by omega⟩ i) (congrFun hr i)

theorem reference_partial_next (inputs : Fin 2 → F) (r : Fin 64)
    (h : 4 ≤ r.val ∧ r.val < 61) :
    referencePre inputs ⟨r.val + 1, by omega⟩ =
      mix M (partialSbox (referencePre inputs ⟨r.val, by omega⟩)) +
        referenceConstant ⟨r.val + 1, by omega⟩ := by
  unfold referencePre referenceState
  rw [run_succ (fun r : Fin 65 => round params3 r) (referenceStart inputs) (show r.val < 65 by omega)]
  have hr := reference_round ⟨r.val, by omega⟩
    (run (fun r : Fin 65 => round params3 r) (referenceStart inputs) r.val)
  have h0 : ¬ r.val < 4 := by omega
  have h1 : ¬ 61 ≤ r.val := by omega
  simp only [h0, h1, false_or] at hr
  funext i
  exact congrArg (· + referenceConstant ⟨r.val + 1, by omega⟩ i) (congrFun hr i)

theorem reference_hash (inputs : Fin 2 → F) :
    MSP.Poseidon.hash2 (inputs 0) (inputs 1) = (mix M (sbox (referencePre inputs 64))) 0 := by
  have hr := reference_round 64 (referenceState inputs 64)
  simp only [show ¬ (64 : Fin 65).val < 4 by decide,
    show 61 ≤ (64 : Fin 65).val by decide, or_true, true_or, ↓reduceIte] at hr
  have he : MSP.Poseidon.hash2 (inputs 0) (inputs 1) = (referenceState inputs 65).get 0 := by
    have hi : (Vector.ofFn inputs : Vector F 2) =
        ⟨#[inputs 0, inputs 1], rfl⟩ := by
      apply Vector.ext
      intro i hi
      interval_cases i <;> rfl
    unfold MSP.Poseidon.hash2
    rw [← hi]
    unfold hash referenceState
    rw [run_full (step := fun r : Fin 65 => round params3 r)]
    simp only [get_ofFn]
    rfl
  rw [he]
  unfold referenceState
  rw [run_succ (fun r : Fin 65 => round params3 r) (referenceStart inputs) (by decide : 64 < 65)]
  exact congrFun hr 0

end MSP.Poseidon.Optimized3
