import Proofs.Effects
import Proofs.Composition
import Proofs.CircuitArithmetic
import Proofs.CircuitGadgets
import Proofs.C6
import Artifacts.FullCompression
import Artifacts.Range
import Artifacts.RangeAmounts
import Artifacts.RangeAddress
import Artifacts.BasicGates
import Artifacts.RelationFragments
import Artifacts.PathIndex
import Artifacts.PublicSignals
import Poseidon.Optimized3Equivalence
import Poseidon.Optimized4Equivalence
import Artifacts.PinnedRangeCompleteness
import Artifacts.InputCompleteness
import Artifacts.CircuitSoundness
import Artifacts.ControlCompleteness
import Artifacts.HashTraceCompleteness
import Artifacts.AssignmentRecoveryBeta
import Artifacts.PathCompletenessGates
import Artifacts.BaseAssignment
import Artifacts.GammaCompleteness
import Artifacts.RangeAssignmentCompleteness
import Artifacts.AssignmentRecoverySmall
import Artifacts.HashAssignmentCompletenessSmall
import Artifacts.ConstraintCoverage
import Artifacts.AssignmentAssembly
import Artifacts.CircuitCompleteness
import Proofs.CircuitModel
import Keccak.Labels
import Keccak.Vectors
import Groth16.KeyData
import Groth16.Encoding
import Proofs.NonVacuityEncoding
import Proofs.NonVacuityFixtureVerified
import Groth16.Group
import Lean.Util.CollectAxioms
import Lean.Elab.Command

/-! Fail the build if a checked theorem starts depending on an admission or
an axiom beyond Lean's standard logical axioms. This audits the named proofs;
it does not discharge their hypotheses or bind the opaque artifact declarations. -/

open Lean Elab Command in
elab "assert_standard_axioms " n:ident : command => do
  let name ← liftCoreM <| Lean.Elab.realizeGlobalConstNoOverloadWithInfo n
  let axioms ← Lean.collectAxioms name
  let allowed : List Name := [`propext, `choice, `Classical.choice, `Quot.sound]
  let extra := axioms.filter fun ax => !allowed.contains ax
  unless extra.isEmpty do
    throwError "{n} depends on nonstandard axioms: {extra}"

assert_standard_axioms MSP.model_theorem
assert_standard_axioms MSP.c5j
assert_standard_axioms MSP.c5k
assert_standard_axioms MSP.c5l
assert_standard_axioms MSP.c5m
assert_standard_axioms MSP.c5n
assert_standard_axioms MSP.step_functional
assert_standard_axioms MSP.run_nodup
assert_standard_axioms MSP.spent_nodup_of_c5b
assert_standard_axioms MSP.composes
assert_standard_axioms MSP.nat_eq_of_field_eq
assert_standard_axioms MSP.value_conservation_iff
assert_standard_axioms MSP.input_sum_pos
assert_standard_axioms MSP.scalar_prime
assert_standard_axioms MSP.boolean_constraint
assert_standard_axioms MSP.isZero_sound
assert_standard_axioms MSP.isZero_complete
assert_standard_axioms MSP.bitsValue_cast
assert_standard_axioms MSP.bitsValue_lt
assert_standard_axioms MSP.num2Bits_range
assert_standard_axioms MSP.c6
assert_standard_axioms MSP.Artifacts.Compression.gamma_of_constraints
assert_standard_axioms MSP.Artifacts.Compression.gamma_of_system
assert_standard_axioms MSP.Artifacts.FullCompression.gamma_of_pinned_r1cs
assert_standard_axioms MSP.Artifacts.Range.first_input_range
assert_standard_axioms MSP.Artifacts.RangeAmounts.all_amount_ranges
assert_standard_axioms MSP.Artifacts.RangeAmounts.integer_conservation
assert_standard_axioms MSP.Artifacts.RangeAddress.address_ranges
assert_standard_axioms MSP.Artifacts.InputNonzero.positive_input_value
assert_standard_axioms MSP.Artifacts.BasicGates.statement_checks
assert_standard_axioms MSP.Artifacts.SinkGates.sink_rules
assert_standard_axioms MSP.Artifacts.ConcreteWitness.R1
assert_standard_axioms MSP.Artifacts.ConcreteWitness.index_cast
assert_standard_axioms MSP.Artifacts.ConcreteWitness.public_gamma
assert_standard_axioms MSP.Artifacts.RelationFragments.relation_of_hash_bindings
assert_standard_axioms MSP.Artifacts.PathIndex.MR_eq_raw_fold
assert_standard_axioms MSP.Artifacts.RelationFragments.relation_of_gadget_hashes
assert_standard_axioms MSP.Poseidon.Optimized.hash10_eq_reference
assert_standard_axioms MSP.Artifacts.PublicSignals.compression_of_pinned_r1cs
assert_standard_axioms MSP.Poseidon.Optimized3.hash2_eq_reference
assert_standard_axioms MSP.Poseidon.Optimized4.hash3_eq_reference
assert_standard_axioms MSP.CircuitCompleteness.num2Bits_complete
assert_standard_axioms MSP.Artifacts.RangeCompleteness.gate_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.first_input_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.second_input_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.first_output_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.second_output_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.public_amount_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.fee_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.recipient_complete
assert_standard_axioms MSP.Artifacts.PinnedRangeCompleteness.authorizer_complete
assert_standard_axioms MSP.Artifacts.InputCompleteness.input_gate_complete
assert_standard_axioms MSP.c1

assert_standard_axioms MSP.Artifacts.ControlCompleteness.complete_holds_of_relation
assert_standard_axioms MSP.Artifacts.HashTraceCompleteness.construct
assert_standard_axioms MSP.Artifacts.AssignmentRecoveryBeta.realizes

assert_standard_axioms MSP.Artifacts.PathCompleteness.complete_path
assert_standard_axioms MSP.Artifacts.BaseAssignment.projections_of_agreement
assert_standard_axioms MSP.Artifacts.GammaCompleteness.base_complete_holds
assert_standard_axioms MSP.Artifacts.RangeAssignmentCompleteness.complete_holds
assert_standard_axioms MSP.Artifacts.AssignmentRecoverySmall.realizes
assert_standard_axioms MSP.Artifacts.HashAssignmentCompletenessSmall.complete
assert_standard_axioms MSP.Artifacts.ConstraintCoverage.satisfied_of_fragments
assert_standard_axioms MSP.Artifacts.AssignmentAssembly.satisfied

assert_standard_axioms MSP.c1c

assert_standard_axioms MSP.circuit_model
assert_standard_axioms MSP.chain_corollary_of_chain

assert_standard_axioms MSP.K_lt
assert_standard_axioms MSP.Keccak.hash_lt
assert_standard_axioms MSP.Keccak.domain_one_one_zero_eq
assert_standard_axioms MSP.Keccak.source_one_zero_nondegenerate
assert_standard_axioms MSP.Groth16.pinnedKey_coordinateChecks
assert_standard_axioms MSP.Groth16.G2Coordinates.onCurve_iff
assert_standard_axioms MSP.Groth16.decodeProof_eq_some_iff
assert_standard_axioms MSP.Groth16.decoded_g2_order
assert_standard_axioms MSP.NonVacuity.decode_encodeSettlement
assert_standard_axioms MSP.NonVacuity.encodeTx_Acc

assert_standard_axioms MSP.w1

assert_standard_axioms BN254.BaseField_is_prime
assert_standard_axioms MSP.Groth16.g1Curve_discriminant_ne_zero
assert_standard_axioms MSP.Groth16.G1Coordinates.toPoint_coordinates
assert_standard_axioms MSP.Groth16.G1Coordinates.toPoint_injective
assert_standard_axioms MSP.Groth16.G1Point.coordinates_toPoint
