#!/usr/bin/env python3
"""Generate exact beta and small-hash affine recovery certificates.

Recovery coefficients are computed modulo the pinned field. Lean checks the
beta substitutions directly; three shared small-hash inverse templates are
transported through exact per-instance coefficient and wire-map certificates.
Every plan preserves ambient wires outside its declared write set and assumes
no circuit satisfaction.
"""
import argparse
from pathlib import Path
import sys
import assignment_plan as ap
import hash_instances as hi
from r1cs_artifact import ROOT, PIN, P, InvalidArtifact, parse_r1cs, require, sha

DESTINATION=ROOT/'formal/Artifacts'


def prepare(data):
    require(sha(data)==PIN,'recovery requires exact pinned R1CS')
    artifact=parse_r1cs(data,pinned_compat=True)
    forms=[hi.scale(-1,artifact['constraints'][11+3*t][2]) for t in range(153)]
    columns,inverse=ap.solve_matrix(forms)
    require(columns==[1]+list(range(111,263)),'beta affine write set changed')
    entries=[]
    for wire,row in zip(columns,inverse):
        constant=(-sum(c*dict(forms[t]).get(0,0) for t,c in row))%P
        entries.append((wire,([(0,constant)] if constant else [])+[(t+1,c) for t,c in row]))
    recovered=dict(entries)
    for t,form in enumerate(forms):
        result=hi.add(*(hi.scale(c,[(0,1)] if w==0 else recovered[w]) for w,c in form))
        require(result==[(t+1,1)],f'inverse recovery failed at output {t}')
    return entries


def lean_form(form):return '['+', '.join(f'({w}, {c})' for w,c in form)+']'


def render(data):
    entries=prepare(data)
    lines=['import Artifacts.AssignmentRecovery','import Artifacts.BetaGatesData','',
        '/-! Exact sparse recovery of the beta affine wires.',f'R1CS SHA-256 `{PIN}`.',
        'Generated by `python3 formal/tools/assignment_recovery.py --write`.',
        'Each recovery row is data; substitution identities are kernel checked separately. -/','',
        'namespace MSP.Artifacts.AssignmentRecoveryBetaData','',
        'open BetaGates AssignmentRecovery','',
        'set_option maxRecDepth 131072','']
    for wire,form in entries:lines += [f'def wire{wire} : Form := {lean_form(form)}','']
    lines += ['def plan : Plan where','  count := 153','  entries := [',
        ',\n'.join(f'    ({wire}, wire{wire})' for wire,_ in entries)+']','',
        "theorem written_eq : plan.written = 1 :: List.range' 111 152 := by decide",'',
        'end MSP.Artifacts.AssignmentRecoveryBetaData','']
    result={'AssignmentRecoveryBetaData.lean':'\n'.join(lines)}
    for block in range(20):
        lines=['import Artifacts.AssignmentRecoveryBetaData','',
            '/-! Kernel-checked substitutions of actual pinned beta output constraints. -/','',
            'namespace MSP.Artifacts.AssignmentRecoveryBetaCertificates','',
            'open BetaGates AssignmentRecovery AssignmentRecoveryBetaData','',
            'set_option maxRecDepth 131072','set_option maxHeartbeats 0','']
        for t in range(8*block,min(8*(block+1),153)):
            lines += [f'theorem output{t} :',
                f'    normalize (substitute (BetaGatesData.output ⟨{t}, by decide⟩) plan.replacement) =',
                f'      normalize [({t+1}, 1)] := by decide','']
        lines += ['end MSP.Artifacts.AssignmentRecoveryBetaCertificates','']
        result[f'AssignmentRecoveryBetaCertificates{block}.lean']='\n'.join(lines)
    lines=[f'import Artifacts.AssignmentRecoveryBetaCertificates{i}' for i in range(20)]+['',
        '/-! An explicit assignment realizing all 153 actual beta fifth-output LCs.',
        'Square/fourth wires and semantic optimized traces are separate obligations. -/','',
        'namespace MSP.Artifacts.AssignmentRecoveryBeta','',
        'open BetaGates AssignmentRecovery AssignmentRecoveryBetaData AssignmentRecoveryBetaCertificates','',
        'set_option maxRecDepth 131072','set_option maxHeartbeats 2000000','',
        'theorem certificates (t : Fin 153) :',
        '    normalize (substitute (BetaGatesData.output t) plan.replacement) =',
        '      normalize [(t.val + 1, 1)] := by','  fin_cases t']
    lines += [f'  · exact output{t}' for t in range(153)]
    lines += ['',
        '/-- Arbitrary fifth-output values are realized without any satisfaction premise. -/',
        'theorem realizes (ambient : Assignment) (desired : ℕ → F) (t : Fin 153) :',
        '    eval (BetaGatesData.output t) (plan.apply ambient desired) = desired t.val :=',
        '  plan.realizes _ _ t.isLt (certificates t) ambient desired','',
        '/-- The 153 affine wires are the complete write set of this construction. -/',
        'theorem preserves (ambient : Assignment) (desired : ℕ → F) (wire : ℕ)',
        '    (h : wire ≠ 1 ∧ (wire < 111 ∨ 263 ≤ wire)) :',
        '    plan.apply ambient desired wire = ambient wire := by',
        '  apply plan.preserves ambient desired wire',
        '  rw [written_eq]',
        "  simp only [List.mem_cons, List.mem_range', not_or]",
        '  constructor','  · exact h.1','  · omega','',
        'end MSP.Artifacts.AssignmentRecoveryBeta','']
    result['AssignmentRecoveryBeta.lean']='\n'.join(lines)
    return result



SMALL_PLAN_PIN = "73eeee9fcb7b6651c1df319d019592f9e0dd5c35d9a5d4941539dd40b065fc7a"


def prepare_small(data):
    require(sha(data)==PIN,'small recovery requires exact pinned R1CS')
    import json
    saved=(ROOT/'formal/Artifacts/assignment-plan.json').read_bytes()
    require(sha(saved)==SMALL_PLAN_PIN,'frozen assignment plan changed')
    blocks=json.loads(saved)['hash_blocks'][1:]
    require(len(blocks)==54,'small hash instance count')
    cs=parse_r1cs(data,pinned_compat=True)['constraints']
    templates=[];instances=[]
    for block in blocks:
        start,end=block['constraint_interval']
        forms=[hi.scale(-1,cs[i+2][2]) for i in range(start,end,3)]
        pivots,remaining=ap.triangular_plan(forms)
        require(not remaining,'small affine matrix is not triangular')
        known={0:[(0,1)]};wires=[];recovered=[]
        for t,w,c in pivots:
            rest=hi.add([(t+1,1)],*(hi.scale(-v,known[j]) for j,v in forms[t] if j!=w))
            known[w]=hi.scale(pow(c,-1,P),rest)
            wires.append(w);recovered.append(known[w])
        slots={w:j+1 for j,w in enumerate(wires)}
        outputs=[hi.add([(0 if w==0 else slots[w],c) for w,c in f]) for f in forms]
        for t,f in enumerate(forms):
            require(hi.add(*(hi.scale(c,known[w]) for w,c in f))==[(t+1,1)],'small recovery substitution')
        template=dict(recovered=recovered,outputs=outputs)
        if template not in templates:templates.append(template)
        instances.append(dict(name=block['name'],wires=wires,template=templates.index(template)))
    require([len(t['recovered']) for t in templates]==[80,86,85],'shared template classes changed')
    require([sum(i['template']==t for i in instances) for t in range(3)]==[46,6,2],
            'shared template multiplicities changed')
    return templates,instances


def render_small(data):
    templates,instances=prepare_small(data)
    result={}
    lines=['import Artifacts.AssignmentRecoverySmallLemmas','',
        '/-! Three shared sparse inverse templates extracted from the pinned R1CS.',
        f'R1CS SHA-256 `{PIN}`. Every use is checked against actual output forms.',
        'Generated by `python3 formal/tools/assignment_recovery.py --write`. -/','',
        'namespace MSP.Artifacts.AssignmentRecoverySmallTemplateData','',
        'open BetaGates AssignmentRecovery','set_option maxRecDepth 131072','']
    for k,t in enumerate(templates):
        n=len(t['recovered'])
        for j,form in enumerate(t['recovered']):
            lines += [f'def wire{k}_{j+1} : Form := {lean_form(form)}','']
        lines += [f'def plan{k} : Plan where',f'  count := {n}',
            '  entries := ['+', '.join(f'({j+1}, wire{k}_{j+1})' for j in range(n))+']','']
        for j,form in enumerate(t['outputs']):lines += [f'def output{k}_{j} : Form := {lean_form(form)}','']
        lines += [f'def outputs{k} : Vector Form {n} :=',
            '  ⟨#['+', '.join(f'output{k}_{j}' for j in range(n))+'], rfl⟩',
            f'def output{k} (t : Fin {n}) : Form := outputs{k}.get t','',
            f'theorem support{k} : ∀ t : Fin {n},',
            f'    (output{k} t).all (fun term => decide (term.1 ≤ {n})) = true := by decide','']
    lines += ['end MSP.Artifacts.AssignmentRecoverySmallTemplateData','']
    result['AssignmentRecoverySmallTemplateData.lean']='\n'.join(lines)
    for k,t in enumerate(templates):
        n=len(t['recovered'])
        lines=['import Artifacts.AssignmentRecoverySmallTemplateData','',
            f'/-! Kernel-checked sparse inverse for shared template {k}. -/','',
            'namespace MSP.Artifacts.AssignmentRecoverySmallTemplateCertificates','',
            'open BetaGates AssignmentRecovery AssignmentRecoverySmallTemplateData',
            'set_option maxRecDepth 131072','set_option maxHeartbeats 0','',
            f'theorem certificate{k} : ∀ t : Fin {n},',
            f'    normalize (substitute (output{k} t) plan{k}.replacement) =',
            '      normalize [(t.val + 1, 1)] := by decide','',
            'end MSP.Artifacts.AssignmentRecoverySmallTemplateCertificates','']
        result[f'AssignmentRecoverySmallTemplateCertificates{k}.lean']='\n'.join(lines)
    lines=['import Artifacts.AssignmentRecoverySmallTemplateData','',
        '/-! Exact physical write sets and sparse recovery plans for all54 small hashes.',
        f'Frozen extraction map SHA-256 `{SMALL_PLAN_PIN}`. -/','',
        'namespace MSP.Artifacts.AssignmentRecoverySmallData','',
        'open BetaGates AssignmentRecovery AssignmentRecoverySmallTemplateData SmallHashGatesData',
        'set_option maxRecDepth 131072','']
    for i,inst in enumerate(instances):
        k=inst['template'];n=len(inst['wires'])
        lines += [f'/-- {inst["name"]} -/',f'def wires{i} : List ℕ := '+repr(inst['wires']),
            f'def plan{i} : Plan where',f'  count := {n}',
            '  entries := ['+', '.join(f'({w}, wire{k}_{j+1})' for j,w in enumerate(inst['wires']))+']',
            f'def wireMap{i} (j : ℕ) : ℕ := (0 :: wires{i}).getD j 0','']
    lines += ['def plans : Vector Plan 54 :=','  ⟨#['+', '.join(f'plan{i}' for i in range(54))+'], rfl⟩',
        'def plan (i : Fin 54) : Plan := plans.get i','',
        'def writeSets : Vector (List ℕ) 54 :=','  ⟨#['+', '.join(f'wires{i}' for i in range(54))+'], rfl⟩',
        'def writeSet (i : Fin 54) : List ℕ := writeSets.get i','',
        'theorem count_eq (i : Fin 54) : (plan i).count = (gate i).tripleCount := by',
        '  fin_cases i <;> rfl','',
        'theorem written_eq (i : Fin 54) : (plan i).written = writeSet i := by',
        '  fin_cases i <;> rfl','',
        'end MSP.Artifacts.AssignmentRecoverySmallData','']
    result['AssignmentRecoverySmallData.lean']='\n'.join(lines)
    for i,inst in enumerate(instances):
        k=inst['template'];n=len(inst['wires'])
        lines=['import Artifacts.AssignmentRecoverySmallData',
            f'import Artifacts.AssignmentRecoverySmallTemplateCertificates{k}','',
            f'/-! Exact affine recovery transport for {inst["name"]}. -/','',
            'namespace MSP.Artifacts.AssignmentRecoverySmallCertificates','',
            'open BetaGates AssignmentRecovery AssignmentRecoverySmall SmallHashGatesData',
            'set_option maxRecDepth 131072','set_option maxHeartbeats 0','',
            f'private theorem forms{i} : ∀ t : Fin {n},',
            f'    normalize (SmallHashGates.output instance{i} t) =',
            f'      normalize (rename (AssignmentRecoverySmallTemplateData.output{k} t)',
            f'        AssignmentRecoverySmallData.wireMap{i}) := by decide','',
            f'private theorem replacements{i} : ∀ j : Fin {n+1},',
            f'    AssignmentRecoverySmallData.plan{i}.replacement',
            f'      (AssignmentRecoverySmallData.wireMap{i} j.val) =',
            f'        AssignmentRecoverySmallTemplateData.plan{k}.replacement j.val := by decide','',
            f'theorem realizes{i} (ambient : Assignment) (desired : ℕ → F) (t : Fin {n}) :',
            f'    eval (SmallHashGates.output instance{i} t)',
            f'      (AssignmentRecoverySmallData.plan{i}.apply ambient desired) = desired t.val := by',
            f'  apply realizes_renamed AssignmentRecoverySmallTemplateData.plan{k}',
            f'    AssignmentRecoverySmallData.plan{i} _ _ AssignmentRecoverySmallData.wireMap{i}',
            '    t.val t.isLt rfl',
            f'    (AssignmentRecoverySmallTemplateCertificates.certificate{k} t) (forms{i} t)',
            '  · intro term hterm',
            f'    have hs := AssignmentRecoverySmallTemplateData.support{k} t',
            '    simp only [List.all_eq_true, decide_eq_true_eq] at hs',
            '    exact hs term hterm',
            '  · intro j hj',f'    exact replacements{i} ⟨j, by change j ≤ {n} at hj; omega⟩','',
            'end MSP.Artifacts.AssignmentRecoverySmallCertificates','']
        result[f'AssignmentRecoverySmallCertificates{i}.lean']='\n'.join(lines)
    lines=[f'import Artifacts.AssignmentRecoverySmallCertificates{i}' for i in range(54)]+['',
        '/-! Explicit complete affine recovery for every actual small-hash output LC.',
        'No satisfaction premise, hash equation or witness-generator behavior is assumed. -/','',
        'namespace MSP.Artifacts.AssignmentRecoverySmall','',
        'open BetaGates AssignmentRecovery AssignmentRecoverySmallData SmallHashGatesData',
        'open AssignmentRecoverySmallCertificates','set_option maxRecDepth 131072',
        'set_option maxHeartbeats 2000000','',
        'theorem realizes (i : Fin 54) (ambient : Assignment) (desired : ℕ → F)',
        '    (t : Fin (gate i).tripleCount) :',
        '    eval (SmallHashGates.output (gate i) t) ((plan i).apply ambient desired) = desired t.val := by',
        '  fin_cases i']
    lines += [f'  · exact realizes{i} ambient desired t' for i in range(54)]
    lines += ['',
        'theorem preserves (i : Fin 54) (ambient : Assignment) (desired : ℕ → F) (wire : ℕ)',
        '    (h : wire ∉ writeSet i) :',
        '    (plan i).apply ambient desired wire = ambient wire := by',
        '  apply (plan i).preserves ambient desired wire',
        '  simpa only [written_eq] using h','',
        'end MSP.Artifacts.AssignmentRecoverySmall','']
    result['AssignmentRecoverySmall.lean']='\n'.join(lines)
    return result

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    args=parser.parse_args()
    data=(ROOT/'build/spend.r1cs').read_bytes()
    result=render(data)
    result.update(render_small(data))
    for name,text in result.items():
        path=DESTINATION/name
        if args.write:
            if not path.exists() or path.read_text()!=text:path.write_text(text)
        else:require(path.read_text()==text,f'{name} differs from exact regeneration')
    print('Beta and all 54 small sparse recovery forms and proof modules match exact regeneration.')


if __name__=='__main__':
    try:main()
    except (InvalidArtifact,OSError,ValueError,KeyError) as error:
        print(f'ERROR: {error}',file=sys.stderr);sys.exit(1)
