#!/usr/bin/env python3
"""Generate exact ordered coverage of all pinned MSP constraints by proved fragments."""
import argparse
import json
import sys
from pathlib import Path
from r1cs_artifact import PIN, ROOT, InvalidArtifact, parse_r1cs, require, sha
from small_hash_gates import MAP, MAP_PIN

DESTINATION = ROOT / 'formal/Artifacts/ConstraintCoverageData.lean'


def segments(mapping):
    require(sha(mapping) == MAP_PIN, 'hash inventory pin changed')
    inventory = json.loads(mapping)
    records = inventory['instances']
    require(len(records) == 54, 'expected 54 small hash instances')
    # (actual start, length, proof family, offset in that family).
    result = [(0, 9, 'gamma', 0), (9, 459, 'beta', 0),
              (468, 6, 'controls', 0), (474, 160, 'ranges', 928),
              (634, 2, 'controls', 18), (636, 61, 'paths', 0),
              (6988, 61, 'paths', 61), (13856, 12, 'controls', 6),
              (13868, 2, 'controls', 20), (13870, 768, 'ranges', 0),
              (14638, 160, 'ranges', 768), (14798, 4, 'controls', 22)]
    result += [(r['constraint_start'], r['constraint_end_exclusive']-r['constraint_start'],
                f'small {i}', 0) for i, r in enumerate(records)]
    return sorted(result)


def validate(rows, count=14802):
    position = 0
    local = {}
    for start, length, family, offset in rows:
        require(start == position, 'coverage has a gap or overlapping actual indices')
        require(length > 0 and offset >= 0, 'invalid fragment slice')
        position += length
        local.setdefault(family, []).extend(range(offset, offset+length))
    require(position == count, 'coverage does not reach the complete pinned system')
    for family, indices in local.items():
        require(sorted(indices) == list(range(len(indices))),
                f'{family}: duplicated or missing local constraint occurrence')
    return local


def group_pieces(rows):
    groups = [[] for _ in range(58)]
    for start, length, family, offset in rows:
        while length:
            group = start // 256
            take = min(length, 256-start%256)
            groups[group].append((family, offset, take))
            start, offset, length = start+take, offset+take, length-take
    return groups


def render(data, mapping):
    require(sha(data) == PIN, 'constraint coverage requires the pinned R1CS')
    artifact = parse_r1cs(data, pinned_compat=True)
    rows = segments(mapping)
    validate(rows, len(artifact['constraints']))
    groups = group_pieces(rows)
    lines = ['import Artifacts.ConstraintCoverageLemmas', '', '/-!',
             '# Exact ordered reconstruction of every pinned constraint', '',
             f'R1CS SHA-256 `{PIN}`.', f'Hash inventory SHA-256 `{MAP_PIN}`.',
             'Generated by `python3 formal/tools/constraint_coverage.py --write`.',
             'Each group equality is checked by kernel reduction, including every',
             'coefficient and original occurrence. No constraint is deduplicated.', '-/', '',
             'namespace MSP.Artifacts.ConstraintCoverage', '',
             'set_option maxRecDepth 65536', 'set_option maxHeartbeats 2000000', '']
    for number, pieces in enumerate(groups):
        items = []
        for family, offset, count in pieces:
            if family.startswith('small '):
                owner = f'(.small {family.split()[1]})'
            else:
                owner = '.' + family
            items.append(f'⟨{owner}, {offset}, {count}⟩')
        lines += [f'def group{number} : List Piece :=', '  [' + ', '.join(items) + ']', '',
                  f'theorem group{number}_eq : Spend.group{number} = expand group{number} := rfl', '']
    lines += ['def groups : List (List Piece) :=',
              '  [' + ', '.join(f'group{i}' for i in range(58)) + ']', '',
              'def ordered : List Constraint := (groups.map expand).flatten', '',
              '/-- Ordered equality preserves every occurrence, including repeated clauses. -/',
              'theorem ordered_eq : Spend.system.constraints = ordered := by',
              '  apply congrArg List.flatten',
              '  change [' + ', '.join(f'Spend.group{i}' for i in range(58)) + '] =',
              '    [' + ', '.join(f'expand group{i}' for i in range(58)) + ']',
              '  apply List.ext_getElem (by rfl)', '  intro i hi hi₂',
              '  change i < 58 at hi', '  interval_cases i']
    lines += [f'  · exact group{i}_eq' for i in range(58)]
    lines += ['', 'end MSP.Artifacts.ConstraintCoverage', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    data, mapping = (ROOT/'build/spend.r1cs').read_bytes(), MAP.read_bytes()
    expected = render(data, mapping)
    if args.write:
        DESTINATION.write_text(expected)
    else:
        require(DESTINATION.read_text() == expected, 'coverage data differs from exact regeneration')
    print('14,802 ordered constraint occurrences partition into gamma9, beta459, small13098, ranges1088, controls26, paths122.')


if __name__ == '__main__':
    try:
        main()
    except (InvalidArtifact, OSError, ValueError, KeyError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        sys.exit(1)
