#!/usr/bin/env python3
"""Deterministically export pinned dispatcher bytes and kernel-checkable facts.

This checks the committed initcode text hash before export. It runs no compiler,
deployment, transaction, or setup. The Lean slice theorem is a byte-extraction
fact, not a proof of the entire creation transaction.
"""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "devnet/build/shielded_pool_dispatcher_init.hex"
TARGET = ROOT / "formal/Chain/DispatcherData.lean"
PIN = "8339dab370f7fc24a7584d48d08df7bd21296b6840a4bc66fbb8165ea35e1bf4"
OFFSET, LENGTH = 59, 1565
PATH = [(0, ".push 2"), (3, ".calldatasize"), (4, ".eq"), (5, ".push 2"),
        (8, ".jumpi"), (48, ".jumpdest"), (49, ".address"), (50, ".push 1"),
        (52, ".txparam"), (53, ".sub"), (54, ".push 2"), (57, ".jumpi"),
        (607, ".jumpdest"), (608, ".push 2"), (611, ".jump"), (624, ".jumpdest"),
        (625, ".push 4"), (630, ".push 1"), (632, ".shl"), (633, ".push 0"),
        (634, ".mstore"), (635, ".push 1"), (637, ".push 0"), (638, ".revert")]
PUSHES = [(0, 2, 288), (5, 2, 48), (50, 1, 2), (54, 2, 607),
          (608, 2, 624), (625, 4, 0x1cda45c5), (630, 1, 227), (633, 0, 0),
          (635, 1, 4), (637, 0, 0)]

def literal(data):
    return "[\n" + ",\n".join("  " + ", ".join(f"0x{x:02x}" for x in data[i:i+24])
                              for i in range(0, len(data), 24)) + "]"

def generate(raw):
    if hashlib.sha256(raw).hexdigest() != PIN:
        raise ValueError("dispatcher initcode text does not match the activation pin")
    init = bytes.fromhex(raw.decode().strip().removeprefix("0x"))
    if len(init) != OFFSET + LENGTH:
        raise ValueError("unexpected constructor/runtime byte layout")
    runtime = init[OFFSET:OFFSET+LENGTH]
    lines = ["import Chain.Pilot", "", "/-! Generated by tools/dispatcher_pilot.py.",
             f"Pinned initcode text SHA256: {PIN}.",
             "This certifies bytes and their extraction, not execution of the creation transaction. -/", "",
             "namespace MSP.Chain.Dispatcher", "", "open Pilot",
             "set_option maxRecDepth 10000", "set_option maxHeartbeats 4000000", "",
             "def initBytes : List UInt8 := " + literal(init), "",
             "def runtimeBytes : List UInt8 := " + literal(runtime), "",
             "theorem init_length : initBytes.length = 1624 := by decide",
             "theorem runtime_length : runtimeBytes.length = 1565 := by decide",
             "theorem runtime_extraction : (initBytes.drop 59).take 1565 = runtimeBytes := by decide", "",
             "/-- D12 links two 32-byte address words after the compiler's runtime. -/",
             "def linkedCode (immutables : List UInt8) : List UInt8 := runtimeBytes ++ immutables", ""]
    for pc, op in PATH:
        lines += [f"theorem decode_{pc} (tail : List UInt8) :",
                  f"    decode (linkedCode tail) {pc} = .ok ({op}) := by rfl"]
    for pc, width, value in PUSHES:
        arithmetic = "0"
        for byte in runtime[pc+1:pc+1+width]:
            arithmetic = f"({arithmetic} * 256 + {byte})"
        lines += [f"theorem push_{pc} (tail : List UInt8) :",
                  f"    pushValue (linkedCode tail) {pc} {width} = {value} := by",
                  f"  have h : (List.range {width}).foldl (fun n j => n * 256 +",
                  f"      ((linkedCode tail)[{pc}+1+j]?.getD 0).toNat) 0 = {value} := by",
                  f"    change {arithmetic} = {value}", "    norm_num",
                  "  unfold pushValue", "  rw [h]", "  norm_num"]
    for pc in [48, 607, 624]:
        lines += [f"theorem jump_{pc} (tail : List UInt8) :",
                  f"    validJump (linkedCode tail) {pc} = true := by rfl"]
    # Constructor operands actually naming the compiler's runtime interval.
    lines += ["", "theorem constructor_length_operand : pushValue initBytes 38 2 = 1565 := by decide",
              "theorem constructor_offset_operand : pushValue initBytes 50 2 = 59 := by decide",
              "", "end MSP.Chain.Dispatcher", ""]
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate(SOURCE.read_bytes())
    if args.check:
        if TARGET.read_text() != text:
            raise SystemExit("generated dispatcher Lean bytes/certificates are stale")
        print("pinned dispatcher bytes and generated Lean source match")
    else:
        TARGET.write_text(text)
        print(TARGET)

if __name__ == "__main__":
    main()
