#!/usr/bin/env python3
"""Emit a checked 10069-torsion point on the actual BN254 twist.

The candidate is just a concrete point; no assumed ambient cardinality is used.
Lean checks its coordinates and all binary group-law steps independently.
"""
import argparse
from pathlib import Path
from groth16_subgroups import point_add, point_def, add_proof, scalar

ROOT = Path(__file__).resolve().parents[2]
COORDS = (
    17104313122165765134751071573954397998910742057160586741504431865092530247148,
    6803298140907275052193374279696798829244532018046680484422159498316181153049,
    20929228109215085641673534002875667749781168108789068628040984026599887111329,
    717535573572059415844575060885625982841398457036564749994433381333260146759,
)
ORDER = 10069


def render():
    initial = (COORDS[:2], COORDS[2:])
    lines = ['import Groth16.Subgroup', '',
        '/-! Generated by tools/groth16_cofactor.py. Every coordinate and group-law',
        'step is checked by the Lean kernel; no ambient group order is assumed. -/', '',
        'namespace MSP.Groth16.Subgroup.Cofactor', '',
        'set_option maxRecDepth 32768', 'set_option maxHeartbeats 2000000', '']
    lines += [line.replace('private def point', 'def point') for line in point_def('point', initial, 2)]
    lines += ['', 'private theorem prefix0 : (1 : ℕ) • point = point := one_nsmul point', '']
    curr, curr_name, n = initial, 'point', 1
    bits = bin(ORDER)[3:]
    for i, bit in enumerate(bits, 1):
        b = bit == '1'
        doubled, m, kind = point_add(curr, curr)
        dname = f'double{i}' if b else f'point{i}'
        lines += point_def(dname, doubled, 2) + ['']
        if b:
            nxt, ms, ks = point_add(doubled, initial)
            rname = f'point{i}'
            lines += point_def(rname, nxt, 2) + ['']
        else:
            nxt, rname = doubled, dname
        nn = 2*n + int(b)
        lines += [f'private theorem prefix{i} : ({nn} : ℕ) • point = {rname} := by',
            f'  apply binaryStep_certificate point {curr_name} {rname} {n} {str(b).lower()} prefix{i-1}']
        lines += add_proof(curr_name, curr_name, dname, m, kind)
        if b:
            lines += [f'  have hsum : {dname} + point = {rname} := by']
            if ks == 'opposite':
                lines += ['    apply opposite_certificate <;> decide']
            elif ks == 'identity':
                lines += [f'    simp [{dname}, {rname}]']
            else:
                lines += [f'    apply add_certificate (m := {scalar(ms)}) <;> decide']
            lines += ['  simpa only [binaryStep, Bool.true_eq, ite_true, hadd] using hsum']
        else:
            lines += ['  simpa only [binaryStep, Bool.false_eq_true, ite_false, add_zero] using hadd']
        lines += ['']
        curr, curr_name, n = nxt, rname, nn
    assert n == ORDER and curr is None
    lines += [f'theorem cofactor_mul_eq_zero : ({ORDER} : ℕ) • point = 0 := prefix{len(bits)}', '',
        'theorem point_ne_zero : point ≠ 0 := G2Coordinates.toTwistPoint_ne_zero _ _', '',
        'end MSP.Groth16.Subgroup.Cofactor', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'formal/Groth16/Cofactor.lean'
    source = render()
    if args.write:
        path.write_text(source)
    else:
        assert path.read_text() == source, 'cofactor certificate differs'
    print('cofactor: exact arithmetic certificate matches')


if __name__ == '__main__':
    main()
