#!/usr/bin/env python3
"""Export only the exact pinned verification-key coordinate data.

Three representations are compared: JSON, Solidity constants, and zkey affine
points. This is artifact binding, not a setup, subgroup, or pairing proof.
"""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
PINS = {
    'contracts/vectors/spend_vkey.json': '2b37d2e021ef759dd2b40f4daa8c0b68aec7f705aa71ee4cf69cb25e55906d7c',
    'contracts/src/Groth16Verifier.sol': '5bcda629ac9fa4317d52aef102281b12419c1c385abfe0fa991c5ed22e906676',
    'build/spend_final.zkey': '587c048b06d68c61dcb0a9a57b51229def97b219b11827042f4a8faa49499376',
    'build/spend.r1cs': 'e2f6fc89bc0e478231935d7dab10fb07316f2c6dab4303e95da1a390ce84f9bf',
}
Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583
P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
DEST = ROOT / 'formal/Groth16/KeyData.lean'


def require(test, message):
    if not test:
        raise ValueError(message)


def coordinate(value):
    require(type(value) is str and value.isascii() and value.isdecimal(), 'coordinate is not decimal text')
    n = int(value)
    require(str(n) == value and 0 <= n < Q, 'coordinate is noncanonical or outside base field')
    return n


def parse_key(data):
    key = json.loads(data)
    require(type(key) is dict, 'key must be an object')
    require(key.get('protocol') == 'groth16' and key.get('curve') == 'bn128', 'wrong proof system/curve')
    require(type(key.get('nPublic')) is int and key['nPublic'] == 3, 'wrong public-input count')

    def g1(a):
        require(type(a) is list and len(a) == 3 and a[2] == '1', 'non-affine G1 encoding')
        return [coordinate(x) for x in a[:2]]

    def g2(a):
        require(type(a) is list and len(a) == 3 and a[2] == ['1', '0'], 'non-affine G2 encoding')
        require(all(type(c) is list and len(c) == 2 for c in a[:2]), 'bad G2 coordinate shape')
        return [coordinate(x) for c in a[:2] for x in c]

    require(type(key.get('IC')) is list and len(key['IC']) == 4, 'wrong IC length')
    return {'alpha1': g1(key['vk_alpha_1']),
            'beta2': g2(key['vk_beta_2']), 'gamma2': g2(key['vk_gamma_2']),
            'delta2': g2(key['vk_delta_2']), 'ic': [g1(a) for a in key['IC']]}


def pinned_key(root=ROOT):
    for rel, digest in PINS.items():
        require(hashlib.sha256((root / rel).read_bytes()).hexdigest() == digest, 'SHA256 mismatch: ' + rel)
    # The native gate uses the zkey's Montgomery decoding and binds both public
    # representations. Exact SHA checks above precede its binary parsing.
    sys.path.insert(0, str(ROOT / 'tooling'))
    import check_activation
    check_activation.check_setup(root / 'build/spend.r1cs', root / 'build/spend_final.zkey',
        root / 'contracts/src/Groth16Verifier.sol', root / 'contracts/vectors/spend_vkey.json')
    return parse_key((root / 'contracts/vectors/spend_vkey.json').read_bytes())


def render_from_pinned(root=ROOT):
    key = pinned_key(root)
    lines = ['import Groth16.Curve', '', '/-! Generated by `python3 formal/tools/groth16_key.py --write`.',
             'All source hashes and all three key representations are checked before export.']
    lines += [f'{rel}: {digest}' for rel, digest in PINS.items()]
    lines += ['No setup or pairing claim follows from this data. -/', '', 'namespace MSP.Groth16', '',
              'set_option maxRecDepth 32768', 'set_option maxHeartbeats 2000000', '',
              'def pinnedKey : VerificationKey where']
    for name in ('alpha1', 'beta2', 'gamma2', 'delta2'):
        lines.append(f'  {name} := ⟨' + ', '.join(map(str, key[name])) + '⟩')
    lines.append('  ic := ![' + ',\n    '.join('⟨' + ', '.join(map(str,a)) + '⟩' for a in key['ic']) + ']')
    lines += ['', '/-- Exact coordinate bounds, non-infinity and curve equations for every key point.',
              'This does not discharge the separate subgroup or setup obligations. -/',
              'theorem pinnedKey_coordinateChecks : pinnedKey.CoordinateChecks := by',
              '  unfold VerificationKey.CoordinateChecks G1Coordinates.Canonical G1Coordinates.Nonzero',
              '    G1Coordinates.OnCurve G2Coordinates.Canonical G2Coordinates.Nonzero G2Coordinates.OnCurve',
              '  decide', '',
              '/-- The committed phase-two key uses the standard EIP-197 G2 generator as gamma. -/',
              'theorem pinnedKey_gamma : pinnedKey.gamma2 = ⟨',
              '    10857046999023057135944570762232829481370756359578518086990519993285655852781,',
              '    11559732032986387107991004021392285783925812861821192530917403151452391805634,',
              '    8495653923123431417604973247489272438418190587263600148770280649306958101930,',
              '    4082367875863433681332203403145435568316851327593401208105741076214120093531⟩ := rfl', '',
              'end MSP.Groth16', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    expected = render_from_pinned()
    if args.write:
        if not DEST.exists() or DEST.read_text() != expected:
            DEST.write_text(expected)
    else:
        require(DEST.read_text() == expected, 'KeyData.lean differs from exact pinned export')
    print('PASS: exact JSON/Solidity/zkey key binding and Lean export')


if __name__ == '__main__':
    main()
