#!/usr/bin/env python3
"""Generate kernel-checkable binary scalar traces for exact pinned key points.

Python selects affine coordinates and slopes. Lean checks every curve equation,
nonzero denominator, slope equation, output coordinate and group-law step.
No primality, group-order or pairing fact is inferred from Python arithmetic.
"""
import argparse
from pathlib import Path
from groth16_key import ROOT, P, Q, PINS, pinned_key


def add(a, b):
    return tuple((x + y) % Q for x, y in zip(a, b))


def neg(a):
    return tuple(-x % Q for x in a)


def sub(a, b):
    return add(a, neg(b))


def mul(a, b):
    if len(a) == 1:
        return (a[0] * b[0] % Q,)
    return ((a[0]*b[0]-a[1]*b[1]) % Q, (a[0]*b[1]+a[1]*b[0]) % Q)


def scale(n, a):
    return tuple(n*x % Q for x in a)


def inv(a):
    if len(a) == 1:
        return (pow(a[0], -1, Q),)
    norm_inv = pow((a[0]*a[0]+a[1]*a[1]) % Q, -1, Q)
    return (a[0]*norm_inv % Q, -a[1]*norm_inv % Q)


def point_add(a, b):
    if a is None or b is None:
        return (b if a is None else a), None, 'identity'
    x,y = a
    xx,yy = b
    if x == xx and y == neg(yy):
        return None, None, 'opposite'
    if x == xx:
        assert y == yy
        m = mul(scale(3,mul(x,x)), inv(scale(2,y)))
        kind = 'double'
    else:
        m = mul(sub(y,yy), inv(sub(x,xx)))
        kind = 'add'
    xr = sub(sub(mul(m,m),x),xx)
    yr = sub(mul(m,sub(x,xr)),y)
    return (xr,yr),m,kind


def scalar(a):
    if len(a) == 1:
        return f'({a[0]} : Fq)'
    return '⟨'+', '.join(map(str,a))+'⟩'


def point_def(name, a, dim):
    if a is None:
        return [f'private def {name} : '+('G1Point' if dim==1 else 'TwistPoint')+' := 0']
    nums = [x for c in a for x in c]
    coord = '⟨'+', '.join(map(str,nums))+'⟩'
    if dim == 1:
        return [f'private def {name} : G1Point :=', f'  G1Coordinates.toPoint {coord} (by unfold G1Coordinates.OnCurve; decide)']
    return [f'private def {name} : TwistPoint :=', f'  G2Coordinates.toTwistPoint {coord} (by unfold G2Coordinates.OnCurve; decide)']


def add_proof(a_name, b_name, r_name, slope, kind):
    lines = [f'  have hadd : {a_name} + {b_name} = {r_name} := by']
    if kind == 'identity':
        lines += [f'    simp [{a_name}, {b_name}, {r_name}]']
    elif kind == 'opposite':
        lines += ['    apply opposite_certificate <;> decide']
    else:
        lines += [f'    apply {"double" if kind=="double" else "add"}_certificate (m := {scalar(slope)}) <;> decide']
    return lines


def render(name, coords, source, curve_proof):
    dim = len(coords)//2
    initial = (tuple(coords[:dim]),tuple(coords[dim:]))
    typ = 'G1Point' if dim==1 else 'TwistPoint'
    meth = 'toPoint' if dim==1 else 'toTwistPoint'
    lines=['import Groth16.Subgroup','','/-! Generated by `python3 formal/tools/groth16_subgroups.py --write`.',
           'Exact source pins are checked before generation. Each affine arithmetic and',
           'binary group step is independently checked in Lean; no external result is trusted.']
    lines += [f'{rel}: {digest}' for rel,digest in PINS.items()]
    lines += ['-/', '',f'namespace MSP.Groth16.Subgroup.{name}', '',
              'set_option maxRecDepth 32768','set_option maxHeartbeats 2000000','',
              f'def point : {typ} := ({source}).{meth} ({curve_proof})','',
              'private theorem prefix0 : (1 : ℕ) • point = point := one_nsmul point','']
    curr=initial; curr_name='point'; n=1
    bits=bin(P)[3:]
    for i,bit in enumerate(bits,1):
        b=bit=='1'
        doubled,m,k=point_add(curr,curr)
        dname=f'double{i}' if b else f'point{i}'
        lines += point_def(dname,doubled,dim)+['']
        if b:
            nxt,ms,ks=point_add(doubled,initial)
            rname=f'point{i}'
            lines += point_def(rname,nxt,dim)+['']
        else:
            nxt=doubled; rname=dname
        nn=2*n+int(b)
        lines += [f'private theorem prefix{i} : ({nn} : ℕ) • point = {rname} := by',
                  f'  apply binaryStep_certificate point {curr_name} {rname} {n} {str(b).lower()} prefix{i-1}']
        lines += add_proof(curr_name,curr_name,dname,m,k)
        if b:
            lines += [f'  have hsum : {dname} + point = {rname} := by']
            if ks=='opposite':lines+=['    apply opposite_certificate <;> decide']
            elif ks=='identity':lines+=[f'    simp [{dname}, {rname}]']
            else:lines += [f'    apply add_certificate (m := {scalar(ms)}) <;> decide']
            lines += ['  simpa only [binaryStep, Bool.true_eq, ite_true, hadd] using hsum']
        else:
            lines += ['  simpa only [binaryStep, Bool.false_eq_true, ite_false, add_zero] using hadd']
        lines += ['']
        curr=nxt;curr_name=rname;n=nn
    assert n==P and curr is None
    lines += ['/-- Exact pinned point killed by the scalar prime, in the actual Mathlib group. -/',
              'theorem p_mul_eq_zero : p • point = 0 :=',f'  prefix{len(bits)}','',f'end MSP.Groth16.Subgroup.{name}','']
    return '\n'.join(lines)


def modules(key):
    args=[('Alpha',key['alpha1'],'pinnedKey.alpha1','pinnedKey_coordinateChecks.1.2.2'),
          ('Base',[1,2],'G1Coordinates.mk 1 2','by unfold G1Coordinates.OnCurve; decide')]
    args += [(f'Ic{i}',point,f'pinnedKey.ic {i}',f'(pinnedKey_coordinateChecks.2.1 {i}).2.2') for i,point in enumerate(key['ic'])]
    args += [('Beta',key['beta2'],'pinnedKey.beta2','pinnedKey_coordinateChecks.2.2.1.2.2'),
             ('Gamma',key['gamma2'],'pinnedKey.gamma2','pinnedKey_coordinateChecks.2.2.2.1.2.2'),
             ('Delta',key['delta2'],'pinnedKey.delta2','pinnedKey_coordinateChecks.2.2.2.2.2.2')]
    return args


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write',action='store_true')
    parser.add_argument('--point',choices=['Base','Alpha','Ic0','Ic1','Ic2','Ic3','Beta','Gamma','Delta'])
    args=parser.parse_args()
    key=pinned_key()
    count=0
    for name,coords,source,proof in modules(key):
        if args.point and name!=args.point:continue
        text=render(name,coords,source,proof)
        path=ROOT/'formal/Groth16'/f'Subgroup{name}.lean'
        if args.write:path.write_text(text)
        elif not path.exists() or path.read_text()!=text:raise SystemExit(f'generated file mismatch: {path}')
        count+=1
    print(f'{count} pinned-point traces '+('written' if args.write else 'reproduced exactly'))


if __name__=='__main__':
    main()
