#!/usr/bin/env python3
"""Export exact power-wire, inverse-stage and write-separation certificates.

R1CS bytes and the source-stage inventory are pinned independently. Every
exported descriptor is then compared with the actual Lean constraint slice;
neither this extraction nor the JSON map is a proof premise.
"""
import argparse
import re
import sys

import small_hash_gates as small
from r1cs_artifact import ROOT, PIN, P, InvalidArtifact, parse_r1cs, require

DESTINATION = ROOT / 'formal/Artifacts'


def prepare(data, mapping):
    records = small.prepare(data, mapping)
    constraints = parse_r1cs(data, pinned_compat=True)['constraints']
    result = []
    for i, record in enumerate(records):
        count, start = record['sbox_triples'], record['constraint_start']
        stages = [None] * count
        for stage, offset in record['sigma_constraint_offsets'].items():
            if offset is None:
                continue
            t = (offset - start) // 3
            require(stages[t] is None, f'instance {i}: duplicate retained stage')
            full = re.fullmatch(r'sigmaF\[(\d+)\]\[(\d+)\]', stage)
            partial = re.fullmatch(r'sigmaP\[(\d+)\]', stage)
            require(full is not None or partial is not None, f'instance {i}: unknown stage')
            stages[t] = ('full', *map(int, full.groups())) if full else ('partial', int(partial[1]))
        require(all(stage is not None for stage in stages), f'instance {i}: missing stage')
        squares, fourths = [], []
        for t in range(count):
            middle = constraints[start + 3*t + 1]
            require(len(middle[1]) == len(middle[2]) == 1, f'instance {i}: power wire is not singleton')
            square, fourth = middle[1][0], middle[2][0]
            require(square[1] == 1 and fourth[1] == P-1, f'instance {i}: power wire coefficient')
            squares.append(square[0]); fourths.append(fourth[0])
        base = squares[0]
        require(squares == list(range(base, base+2*count, 2)) and
                fourths == list(range(base+1, base+2*count, 2)), f'instance {i}: power wire schedule')
        input_wires = {int(w) for form in record['input_forms'] for w, _ in form}
        require(not input_wires.intersection(squares + fourths), f'instance {i}: input overwritten')
        result.append((record, base, stages))
    return result


def render_instance(i, record, base, stages):
    def stage_expr(stage):
        if stage[0] == 'full':
            return f'.inl (⟨{stage[1]}, by decide⟩, ⟨{stage[2]}, by decide⟩)'
        return f'.inr ⟨{stage[1]}, by decide⟩'
    lines = ['import Artifacts.HashAssignmentCompletenessPowers',
             'import Artifacts.AssignmentRecoverySmallData', '',
             f'/-! Exact completeness layout for {record["name"]}.',
             f'R1CS SHA-256 `{PIN}`. Inventory SHA-256 `{small.MAP_PIN}`.',
             'Generated by `formal/tools/hash_assignment_completeness.py`.',
             'All descriptors, inverse-stage identities and write exclusions are kernel checked. -/', '',
             'namespace MSP.Artifacts.HashAssignmentCompletenessData', '',
             'open BetaGates SmallHashGates SmallHashGatesData HashAssignmentCompleteness',
             'open AssignmentRecoverySmallData', '',
             'set_option maxRecDepth 131072', 'set_option maxHeartbeats 0', '',
             f'def stages{i} : StageMap instance{i} where',
             '  atStage := ![' + ', '.join(stage_expr(stage) for stage in stages) + ']',
             '  full := by', '    intro r j t h',
             '    fin_cases r <;> fin_cases j <;> cases h <;> rfl',
             '  partial_eq := by decide',
             '  valid := by intro t; fin_cases t <;> rfl', '',
             f'def powers{i} : PowerLayout instance{i} where',
             f'  wire := fun k => {base} + 2 * k.1.val + k.2.val',
             '  injective := by', '    intro a b h',
             '    have ha := a.2.isLt', '    have hb := b.2.isLt',
             '    apply Prod.ext <;> apply Fin.ext <;> dsimp at h ⊢ <;> omega',
             '  nonzero := by intro k; omega',
             '  square := by decide', '  fourth := by decide', '',
             f'theorem separate{i} : WriteSeparation powers{i} plan{i} where',
             '  powers := by decide', '  inputs := by decide', '',
             'end MSP.Artifacts.HashAssignmentCompletenessData', '']
    return '\n'.join(lines)


def outputs(data, mapping):
    prepared = prepare(data, mapping)
    result = {f'HashAssignmentCompletenessData{i}.lean': render_instance(i, *args)
              for i, args in enumerate(prepared)}
    result['HashAssignmentCompletenessData.lean'] = '\n'.join(
        f'import Artifacts.HashAssignmentCompletenessData{i}' for i in range(54)) + '\n'
    result['HashAssignmentCompletenessSmall.lean'] = render_complete(prepared)
    return result


def render_complete(prepared):
    lines = ['import Artifacts.HashAssignmentCompleteness',
             'import Artifacts.HashAssignmentCompletenessData',
             'import Artifacts.AssignmentRecoverySmall',
             'import Artifacts.SmallHashGatesAffineCertificates', '',
             '/-! Explicit witnesses for all 54 actual small-hash constraint slices.',
             'Every plan, wire layout, stage map and affine equation is instantiated',
             'with a kernel-checked certificate. Only the ambient constant-wire',
             'normalization is a premise. Generated by hash_assignment_completeness.py. -/', '',
             'namespace MSP.Artifacts.HashAssignmentCompletenessSmall', '',
             'open BetaGates SmallHashGates SmallHashGatesData HashAssignmentCompleteness',
             'open HashAssignmentCompletenessData SmallHashGatesAffineCertificates',
             'open AssignmentRecovery AssignmentRecoverySmallData', '',
             'set_option maxRecDepth 131072', 'set_option maxHeartbeats 2000000', '',
             'attribute [local irreducible] MSP.Poseidon.hash2 MSP.Poseidon.hash3', '',
             'private theorem h2_reference (a b : F) : MSP.Poseidon.hash2 a b = H2 a b := by',
             '  delta H2', '  rfl', '',
             'private theorem h3_reference (a b c : F) : MSP.Poseidon.hash3 a b c = H3 a b c := by',
             '  delta H3', '  rfl', '',
             'structure Kit (g : Instance) where',
             '  scheme : Scheme g.arity g.partialRounds',
             '  affine : AffineCertificates g scheme',
             '  signs : ∀ t, TripleSigns g t',
             '  powers : PowerLayout g', '  plan : Plan',
             '  separate : WriteSeparation powers plan',
             '  stages : StageMap g', '  recovery : RecoveryCorrect g plan', '']
    for i, (record, _, _) in enumerate(prepared):
        lines += [f'def kit{i} : Kit instance{i} where',
                  f'  scheme := scheme{record["width"]}', f'  affine := affine{i}',
                  f'  signs := SmallHashGatesCertificates.signs ⟨{i}, by decide⟩',
                  f'  powers := powers{i}', f'  plan := plan{i}', f'  separate := separate{i}',
                  f'  stages := stages{i}',
                  f'  recovery := AssignmentRecoverySmall.realizes ⟨{i}, by decide⟩', '']
    lines += ['def kit (i : Fin 54) : Kit (gate i) :=', '  match i with']
    lines += [f'  | ⟨{i}, _⟩ => kit{i}' for i in range(54)]
    lines += ['  | ⟨n + 54, h⟩ => False.elim (by omega)']
    lines += ['',
              'noncomputable def assignment (i : Fin 54) (ambient : Assignment) : Assignment :=',
              '  buildAssignment (kit i).scheme (kit i).powers (kit i).plan (kit i).stages ambient', '',
              'theorem zero (i : Fin 54) (ambient : Assignment) :',
              '    assignment i ambient 0 = ambient 0 :=',
              '  buildAssignment_zero _ _ _ _ _', '',
              'theorem inputs (i : Fin 54) (ambient : Assignment) (j : Fin (gate i).arity) :',
              '    eval ((gate i).inputForms j) (assignment i ambient) =',
              '      eval ((gate i).inputForms j) ambient :=',
              '  buildAssignment_inputs _ _ _ (kit i).separate _ _ _', '',
              'theorem complete (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :',
              '    (∀ c ∈ (gate i).constraints, c.Holds (assignment i ambient)) ∧',
              '    eval (gate i).outputForm (assignment i ambient) =',
              '      (kit i).scheme.hash (ambientInputs (gate i) ambient) :=',
              '  buildAssignment_complete _ (kit i).affine (kit i).signs _ _ (kit i).separate',
              '    _ (kit i).recovery ambient hz', '',
              'theorem assignment_hash (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :',
              '    eval (gate i).outputForm (assignment i ambient) =',
              '      (kit i).scheme.hash (ambientInputs (gate i) (assignment i ambient)) := by',
              '  have hi : ambientInputs (gate i) (assignment i ambient) =',
              '      ambientInputs (gate i) ambient := funext (inputs i ambient)',
              '  rw [hi]', '  exact (complete i ambient hz).2', '',
              '/-- The constructed witness has the exact reference H2/H3 interface. -/',
              'theorem hash_binding (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :',
              '    HashBinding (assignment i ambient) i := by', '  fin_cases i']
    for i, (record, _, _) in enumerate(prepared):
        width = record['width']
        hashname = 'hash2' if width == 3 else 'hash3'
        assign = f'(assignment ⟨{i}, by decide⟩ ambient)'
        params = ' '.join(f'(eval (inputAt instance{i} {j}) {assign})' for j in range(record['arity']))
        href = 'h2_reference _ _' if width == 3 else 'h3_reference _ _ _'
        lines += [f'  · have hh := assignment_hash ⟨{i}, by decide⟩ ambient hz',
                  f'    rw [show (kit ⟨{i}, by decide⟩).scheme = scheme{width} from rfl] at hh',
                  f'    erw [scheme{width}_hash, MSP.Poseidon.Optimized{width}.{hashname}_eq_reference] at hh',
                  f'    change eval instance{i}.outputForm {assign} = H{record["arity"]} {params}',
                  f'    exact hh.trans ({href})']
    lines += ['',
              'theorem preserves (i : Fin 54) (ambient : Assignment) (wire : ℕ)',
              '    (hrecovery : wire ∉ (kit i).plan.written)',
              '    (hpowers : ∀ k, (kit i).powers.wire k ≠ wire) :',
              '    assignment i ambient wire = ambient wire :=',
              '  buildAssignment_preserves _ _ _ _ _ _ hrecovery hpowers', '',
              'end MSP.Artifacts.HashAssignmentCompletenessSmall', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    generated = outputs((ROOT/'build/spend.r1cs').read_bytes(), small.MAP.read_bytes())
    for name, expected in generated.items():
        path = DESTINATION/name
        if args.write:
            path.write_text(expected)
        else:
            require(path.read_text() == expected, f'{name} differs from exact regeneration')
    print('All 54 power layouts, inverse-stage maps and write-separation certificates match exact regeneration.')


if __name__ == '__main__':
    try:
        main()
    except (InvalidArtifact, OSError, ValueError, KeyError) as error:
        print(f'ERROR: {error}', file=sys.stderr)
        sys.exit(1)
