#!/usr/bin/env python3
"""Generate ordinary Lean kernel certificates for the fixed W1 Poseidon calls.

The Python values are candidate numerals. Every exported hash equality is
proved by ordinary Lean `decide`; no Python evaluation is trusted by the proof.
"""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'formal/Proofs'
PARAMS = ROOT / 'reference/poseidon_bn254_constants.json'
PIN = 'aa4ff490f85bd66cdee8a926e24471d854f3e575d4fed354e0dbd550c77a59a2'
P = 21888242871839275222246405745257275088548364400416034343698204186575808495617
D = 4968480372713856270053508398811659268951190880053845541428304835575363535147
NS = 'MSP.NonVacuity.PoseidonFixture'


def compute():
    assert hashlib.sha256(PARAMS.read_bytes()).hexdigest() == PIN
    params = json.loads(PARAMS.read_text())
    assert int(params['prime']) == P
    def h(a):
        t = len(a) + 1
        c = params[f't{t}']
        rf, rp = int(c['rounds_f']), int(c['rounds_p'])
        rc = list(map(int, c['C'])); matrix = [list(map(int,r)) for r in c['M']]
        state = [0] + list(a)
        for r in range(rf + rp):
            state = [(state[j] + rc[r*t+j]) % P for j in range(t)]
            for j in range(t):
                if r < rf//2 or rf//2+rp <= r or j == 0:
                    state[j] = pow(state[j], 5, P)
            state = [sum(matrix[i][j]*state[j] for j in range(t)) % P for i in range(t)]
        return state[0]
    calls = []; values = {'domain': D}
    def record(name, args):
        out = h(args); calls.append((name,args,out)); values[name]=out
        return out
    for k in (1,2):
        pk = record(f'pk{k}', [1,k,0])
        inn = record(f'inner{k}', [pk,k])
        record('leaf' if k==1 else 'dummyLeaf', [2,inn,2 if k==1 else 0])
    record('sink0', [2,1,0]); record('sink1', [2,2,0])
    for k in (1,2):
        nk=record(f'nfKey{k}',[D,k])
        oc=record(f'occurrence{k}',[values['leaf' if k==1 else 'dummyLeaf'],0])
        record(f'nf{k}',[4,nk,oc])
    zeros=[0]
    for l in range(20): zeros.append(h([zeros[-1],zeros[-1]]))
    real=[values['leaf']]; dummy=[values['dummyLeaf']]
    for l in range(20): real.append(record(f'real{l}',[real[-1],zeros[l]]))
    for l in range(20): dummy.append(record(f'dummy{l}',[dummy[-1],0]))
    return values,calls,zeros,real,dummy


def header(imports, comment):
    return '\n'.join('import '+i for i in imports) + f'\n\n/-! {comment} Generated by tools/nonvacuity_poseidon.py. -/\n\nnamespace {NS}\n\nset_option maxRecDepth 32768\nset_option maxHeartbeats 2000000\n\n'


def generate():
    values,calls,zeros,real,dummy=compute(); files={}
    data=header(['Spec.Hash'],f'Concrete W1 values, parameter SHA256 {PIN}.')
    for name,value in values.items(): data+=f'def {name} : ℕ := {value}\n'
    for name,nums in [('zeroValues',zeros),('realValues',real),('dummyValues',dummy)]:
        data+=f'\ndef {name} : Fin 21 → F := !['+',\n  '.join(map(str,nums))+']\n'
    files['NonVacuityPoseidonData.lean']=data+f'\nend {NS}\n'
    # Five bounded modules keep independent finite reductions separable.
    groups=[('Base',calls[:14])]+[(f'Nodes{i}',calls[14+i*10:14+(i+1)*10]) for i in range(4)]
    for group,items in groups:
        text=header(['Proofs.NonVacuityPoseidonData'],'Finite concrete reference-hash equalities.')
        for name,args,out in items:
            fn='H2' if len(args)==2 else 'H3'
            text+=f'theorem {name}_hash : {fn} '+' '.join(f'({v} : F)' for v in args)+f' = ({out} : F) := by\n  unfold {fn}\n  decide\n\n'
        files[f'NonVacuityPoseidon{group}.lean']=text+f'end {NS}\n'
    text=header(['Proofs.NonVacuityPoseidonData','Proofs.C6'],'Reuse the previously checked zero-hash constants.')
    text+='theorem zero_value (i : Fin 21) : Z i.val = zeroValues i := by\n  fin_cases i\n'
    for i in range(21):
        if i==0:text+='  · rfl\n'
        elif i<20:text+=f'  · rw [← zero_constants {i} (by decide)]\n    rfl\n'
        else:text+='  · rw [z_eq_zeroHash, poseidon_empty_root]\n    rfl\n'
    for i in range(20):
        text+=f'\ntheorem zero{i}_hash : H2 ({zeros[i]} : F) ({zeros[i]} : F) = ({zeros[i+1]} : F) := by\n'
        text+=f'  have h := zero_value ⟨{i+1}, by decide⟩\n  change H2 (Z {i}) (Z {i}) = _ at h\n  rw [zero_value ⟨{i}, by decide⟩] at h\n  exact h\n'
    files['NonVacuityPoseidonZeros.lean']=text+f'\nend {NS}\n'
    return files


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--write',action='store_true');args=parser.parse_args()
    files=generate()
    for name,text in files.items():
        path=OUT/name
        if args.write:
            if not path.exists() or path.read_text()!=text:path.write_text(text)
        else: assert path.read_text()==text, name+' differs from deterministic generation'
    print(f'PASS: {len(files)} exact W1 Poseidon certificate modules')


if __name__=='__main__':main()
