import Artifacts.ConstraintCoverageLemmas

/-!
# Exact ordered reconstruction of every pinned constraint

R1CS SHA-256 `e2f6fc89bc0e478231935d7dab10fb07316f2c6dab4303e95da1a390ce84f9bf`.
Hash inventory SHA-256 `6f90e7cd87fb9a3c473d83f665cefd3392ba6363d1f96eb92baf133a10f09368`.
Generated by `python3 formal/tools/constraint_coverage.py --write`.
Each group equality is checked by kernel reduction, including every
coefficient and original occurrence. No constraint is deduplicated.
-/

namespace MSP.Artifacts.ConstraintCoverage

set_option maxRecDepth 65536
set_option maxHeartbeats 2000000

def group0 : List Piece :=
  [⟨.gamma, 0, 9⟩, ⟨.beta, 0, 247⟩]

theorem group0_eq : Spend.group0 = expand group0 := rfl

def group1 : List Piece :=
  [⟨.beta, 247, 212⟩, ⟨.controls, 0, 6⟩, ⟨.ranges, 928, 38⟩]

theorem group1_eq : Spend.group1 = expand group1 := rfl

def group2 : List Piece :=
  [⟨.ranges, 966, 122⟩, ⟨.controls, 18, 2⟩, ⟨.paths, 0, 61⟩, ⟨(.small 0), 0, 71⟩]

theorem group2_eq : Spend.group2 = expand group2 := rfl

def group3 : List Piece :=
  [⟨(.small 0), 71, 169⟩, ⟨(.small 1), 0, 87⟩]

theorem group3_eq : Spend.group3 = expand group3 := rfl

def group4 : List Piece :=
  [⟨(.small 1), 87, 153⟩, ⟨(.small 2), 0, 103⟩]

theorem group4_eq : Spend.group4 = expand group4 := rfl

def group5 : List Piece :=
  [⟨(.small 2), 103, 155⟩, ⟨(.small 3), 0, 101⟩]

theorem group5_eq : Spend.group5 = expand group5 := rfl

def group6 : List Piece :=
  [⟨(.small 3), 101, 139⟩, ⟨(.small 4), 0, 117⟩]

theorem group6_eq : Spend.group6 = expand group6 := rfl

def group7 : List Piece :=
  [⟨(.small 4), 117, 123⟩, ⟨(.small 5), 0, 133⟩]

theorem group7_eq : Spend.group7 = expand group7 := rfl

def group8 : List Piece :=
  [⟨(.small 5), 133, 107⟩, ⟨(.small 6), 0, 149⟩]

theorem group8_eq : Spend.group8 = expand group8 := rfl

def group9 : List Piece :=
  [⟨(.small 6), 149, 91⟩, ⟨(.small 7), 0, 165⟩]

theorem group9_eq : Spend.group9 = expand group9 := rfl

def group10 : List Piece :=
  [⟨(.small 7), 165, 75⟩, ⟨(.small 8), 0, 181⟩]

theorem group10_eq : Spend.group10 = expand group10 := rfl

def group11 : List Piece :=
  [⟨(.small 8), 181, 59⟩, ⟨(.small 9), 0, 197⟩]

theorem group11_eq : Spend.group11 = expand group11 := rfl

def group12 : List Piece :=
  [⟨(.small 9), 197, 43⟩, ⟨(.small 10), 0, 213⟩]

theorem group12_eq : Spend.group12 = expand group12 := rfl

def group13 : List Piece :=
  [⟨(.small 10), 213, 27⟩, ⟨(.small 11), 0, 229⟩]

theorem group13_eq : Spend.group13 = expand group13 := rfl

def group14 : List Piece :=
  [⟨(.small 11), 229, 11⟩, ⟨(.small 12), 0, 240⟩, ⟨(.small 13), 0, 5⟩]

theorem group14_eq : Spend.group14 = expand group14 := rfl

def group15 : List Piece :=
  [⟨(.small 13), 5, 235⟩, ⟨(.small 14), 0, 21⟩]

theorem group15_eq : Spend.group15 = expand group15 := rfl

def group16 : List Piece :=
  [⟨(.small 14), 21, 219⟩, ⟨(.small 15), 0, 37⟩]

theorem group16_eq : Spend.group16 = expand group16 := rfl

def group17 : List Piece :=
  [⟨(.small 15), 37, 203⟩, ⟨(.small 16), 0, 53⟩]

theorem group17_eq : Spend.group17 = expand group17 := rfl

def group18 : List Piece :=
  [⟨(.small 16), 53, 187⟩, ⟨(.small 17), 0, 69⟩]

theorem group18_eq : Spend.group18 = expand group18 := rfl

def group19 : List Piece :=
  [⟨(.small 17), 69, 171⟩, ⟨(.small 18), 0, 85⟩]

theorem group19_eq : Spend.group19 = expand group19 := rfl

def group20 : List Piece :=
  [⟨(.small 18), 85, 155⟩, ⟨(.small 19), 0, 101⟩]

theorem group20_eq : Spend.group20 = expand group20 := rfl

def group21 : List Piece :=
  [⟨(.small 19), 101, 139⟩, ⟨(.small 20), 0, 117⟩]

theorem group21_eq : Spend.group21 = expand group21 := rfl

def group22 : List Piece :=
  [⟨(.small 20), 117, 123⟩, ⟨(.small 21), 0, 133⟩]

theorem group22_eq : Spend.group22 = expand group22 := rfl

def group23 : List Piece :=
  [⟨(.small 21), 133, 107⟩, ⟨(.small 22), 0, 149⟩]

theorem group23_eq : Spend.group23 = expand group23 := rfl

def group24 : List Piece :=
  [⟨(.small 22), 149, 91⟩, ⟨(.small 23), 0, 165⟩]

theorem group24_eq : Spend.group24 = expand group24 := rfl

def group25 : List Piece :=
  [⟨(.small 23), 165, 93⟩, ⟨(.small 24), 0, 163⟩]

theorem group25_eq : Spend.group25 = expand group25 := rfl

def group26 : List Piece :=
  [⟨(.small 24), 163, 77⟩, ⟨(.small 25), 0, 179⟩]

theorem group26_eq : Spend.group26 = expand group26 := rfl

def group27 : List Piece :=
  [⟨(.small 25), 179, 76⟩, ⟨.paths, 61, 61⟩, ⟨(.small 26), 0, 119⟩]

theorem group27_eq : Spend.group27 = expand group27 := rfl

def group28 : List Piece :=
  [⟨(.small 26), 119, 121⟩, ⟨(.small 27), 0, 135⟩]

theorem group28_eq : Spend.group28 = expand group28 := rfl

def group29 : List Piece :=
  [⟨(.small 27), 135, 105⟩, ⟨(.small 28), 0, 151⟩]

theorem group29_eq : Spend.group29 = expand group29 := rfl

def group30 : List Piece :=
  [⟨(.small 28), 151, 107⟩, ⟨(.small 29), 0, 149⟩]

theorem group30_eq : Spend.group30 = expand group30 := rfl

def group31 : List Piece :=
  [⟨(.small 29), 149, 91⟩, ⟨(.small 30), 0, 165⟩]

theorem group31_eq : Spend.group31 = expand group31 := rfl

def group32 : List Piece :=
  [⟨(.small 30), 165, 75⟩, ⟨(.small 31), 0, 181⟩]

theorem group32_eq : Spend.group32 = expand group32 := rfl

def group33 : List Piece :=
  [⟨(.small 31), 181, 59⟩, ⟨(.small 32), 0, 197⟩]

theorem group33_eq : Spend.group33 = expand group33 := rfl

def group34 : List Piece :=
  [⟨(.small 32), 197, 43⟩, ⟨(.small 33), 0, 213⟩]

theorem group34_eq : Spend.group34 = expand group34 := rfl

def group35 : List Piece :=
  [⟨(.small 33), 213, 27⟩, ⟨(.small 34), 0, 229⟩]

theorem group35_eq : Spend.group35 = expand group35 := rfl

def group36 : List Piece :=
  [⟨(.small 34), 229, 11⟩, ⟨(.small 35), 0, 240⟩, ⟨(.small 36), 0, 5⟩]

theorem group36_eq : Spend.group36 = expand group36 := rfl

def group37 : List Piece :=
  [⟨(.small 36), 5, 235⟩, ⟨(.small 37), 0, 21⟩]

theorem group37_eq : Spend.group37 = expand group37 := rfl

def group38 : List Piece :=
  [⟨(.small 37), 21, 219⟩, ⟨(.small 38), 0, 37⟩]

theorem group38_eq : Spend.group38 = expand group38 := rfl

def group39 : List Piece :=
  [⟨(.small 38), 37, 203⟩, ⟨(.small 39), 0, 53⟩]

theorem group39_eq : Spend.group39 = expand group39 := rfl

def group40 : List Piece :=
  [⟨(.small 39), 53, 187⟩, ⟨(.small 40), 0, 69⟩]

theorem group40_eq : Spend.group40 = expand group40 := rfl

def group41 : List Piece :=
  [⟨(.small 40), 69, 171⟩, ⟨(.small 41), 0, 85⟩]

theorem group41_eq : Spend.group41 = expand group41 := rfl

def group42 : List Piece :=
  [⟨(.small 41), 85, 155⟩, ⟨(.small 42), 0, 101⟩]

theorem group42_eq : Spend.group42 = expand group42 := rfl

def group43 : List Piece :=
  [⟨(.small 42), 101, 139⟩, ⟨(.small 43), 0, 117⟩]

theorem group43_eq : Spend.group43 = expand group43 := rfl

def group44 : List Piece :=
  [⟨(.small 43), 117, 123⟩, ⟨(.small 44), 0, 133⟩]

theorem group44_eq : Spend.group44 = expand group44 := rfl

def group45 : List Piece :=
  [⟨(.small 44), 133, 107⟩, ⟨(.small 45), 0, 149⟩]

theorem group45_eq : Spend.group45 = expand group45 := rfl

def group46 : List Piece :=
  [⟨(.small 45), 149, 91⟩, ⟨(.small 46), 0, 165⟩]

theorem group46_eq : Spend.group46 = expand group46 := rfl

def group47 : List Piece :=
  [⟨(.small 46), 165, 75⟩, ⟨(.small 47), 0, 181⟩]

theorem group47_eq : Spend.group47 = expand group47 := rfl

def group48 : List Piece :=
  [⟨(.small 47), 181, 59⟩, ⟨(.small 48), 0, 197⟩]

theorem group48_eq : Spend.group48 = expand group48 := rfl

def group49 : List Piece :=
  [⟨(.small 48), 197, 43⟩, ⟨(.small 49), 0, 213⟩]

theorem group49_eq : Spend.group49 = expand group49 := rfl

def group50 : List Piece :=
  [⟨(.small 49), 213, 45⟩, ⟨(.small 50), 0, 211⟩]

theorem group50_eq : Spend.group50 = expand group50 := rfl

def group51 : List Piece :=
  [⟨(.small 50), 211, 29⟩, ⟨(.small 51), 0, 227⟩]

theorem group51_eq : Spend.group51 = expand group51 := rfl

def group52 : List Piece :=
  [⟨(.small 51), 227, 28⟩, ⟨(.small 52), 0, 228⟩]

theorem group52_eq : Spend.group52 = expand group52 := rfl

def group53 : List Piece :=
  [⟨(.small 52), 228, 30⟩, ⟨(.small 53), 0, 226⟩]

theorem group53_eq : Spend.group53 = expand group53 := rfl

def group54 : List Piece :=
  [⟨(.small 53), 226, 32⟩, ⟨.controls, 6, 12⟩, ⟨.controls, 20, 2⟩, ⟨.ranges, 0, 210⟩]

theorem group54_eq : Spend.group54 = expand group54 := rfl

def group55 : List Piece :=
  [⟨.ranges, 210, 256⟩]

theorem group55_eq : Spend.group55 = expand group55 := rfl

def group56 : List Piece :=
  [⟨.ranges, 466, 256⟩]

theorem group56_eq : Spend.group56 = expand group56 := rfl

def group57 : List Piece :=
  [⟨.ranges, 722, 46⟩, ⟨.ranges, 768, 160⟩, ⟨.controls, 22, 4⟩]

theorem group57_eq : Spend.group57 = expand group57 := rfl

def groups : List (List Piece) :=
  [group0, group1, group2, group3, group4, group5, group6, group7, group8, group9, group10, group11, group12, group13, group14, group15, group16, group17, group18, group19, group20, group21, group22, group23, group24, group25, group26, group27, group28, group29, group30, group31, group32, group33, group34, group35, group36, group37, group38, group39, group40, group41, group42, group43, group44, group45, group46, group47, group48, group49, group50, group51, group52, group53, group54, group55, group56, group57]

def ordered : List Constraint := (groups.map expand).flatten

/-- Ordered equality preserves every occurrence, including repeated clauses. -/
theorem ordered_eq : Spend.system.constraints = ordered := by
  apply congrArg List.flatten
  change [Spend.group0, Spend.group1, Spend.group2, Spend.group3, Spend.group4, Spend.group5, Spend.group6, Spend.group7, Spend.group8, Spend.group9, Spend.group10, Spend.group11, Spend.group12, Spend.group13, Spend.group14, Spend.group15, Spend.group16, Spend.group17, Spend.group18, Spend.group19, Spend.group20, Spend.group21, Spend.group22, Spend.group23, Spend.group24, Spend.group25, Spend.group26, Spend.group27, Spend.group28, Spend.group29, Spend.group30, Spend.group31, Spend.group32, Spend.group33, Spend.group34, Spend.group35, Spend.group36, Spend.group37, Spend.group38, Spend.group39, Spend.group40, Spend.group41, Spend.group42, Spend.group43, Spend.group44, Spend.group45, Spend.group46, Spend.group47, Spend.group48, Spend.group49, Spend.group50, Spend.group51, Spend.group52, Spend.group53, Spend.group54, Spend.group55, Spend.group56, Spend.group57] =
    [expand group0, expand group1, expand group2, expand group3, expand group4, expand group5, expand group6, expand group7, expand group8, expand group9, expand group10, expand group11, expand group12, expand group13, expand group14, expand group15, expand group16, expand group17, expand group18, expand group19, expand group20, expand group21, expand group22, expand group23, expand group24, expand group25, expand group26, expand group27, expand group28, expand group29, expand group30, expand group31, expand group32, expand group33, expand group34, expand group35, expand group36, expand group37, expand group38, expand group39, expand group40, expand group41, expand group42, expand group43, expand group44, expand group45, expand group46, expand group47, expand group48, expand group49, expand group50, expand group51, expand group52, expand group53, expand group54, expand group55, expand group56, expand group57]
  apply List.ext_getElem (by rfl)
  intro i hi hi₂
  change i < 58 at hi
  interval_cases i
  · exact group0_eq
  · exact group1_eq
  · exact group2_eq
  · exact group3_eq
  · exact group4_eq
  · exact group5_eq
  · exact group6_eq
  · exact group7_eq
  · exact group8_eq
  · exact group9_eq
  · exact group10_eq
  · exact group11_eq
  · exact group12_eq
  · exact group13_eq
  · exact group14_eq
  · exact group15_eq
  · exact group16_eq
  · exact group17_eq
  · exact group18_eq
  · exact group19_eq
  · exact group20_eq
  · exact group21_eq
  · exact group22_eq
  · exact group23_eq
  · exact group24_eq
  · exact group25_eq
  · exact group26_eq
  · exact group27_eq
  · exact group28_eq
  · exact group29_eq
  · exact group30_eq
  · exact group31_eq
  · exact group32_eq
  · exact group33_eq
  · exact group34_eq
  · exact group35_eq
  · exact group36_eq
  · exact group37_eq
  · exact group38_eq
  · exact group39_eq
  · exact group40_eq
  · exact group41_eq
  · exact group42_eq
  · exact group43_eq
  · exact group44_eq
  · exact group45_eq
  · exact group46_eq
  · exact group47_eq
  · exact group48_eq
  · exact group49_eq
  · exact group50_eq
  · exact group51_eq
  · exact group52_eq
  · exact group53_eq
  · exact group54_eq
  · exact group55_eq
  · exact group56_eq
  · exact group57_eq

end MSP.Artifacts.ConstraintCoverage
