import Artifacts.HashAssignmentCompleteness
import Artifacts.HashAssignmentCompletenessData
import Artifacts.AssignmentRecoverySmall
import Artifacts.SmallHashGatesAffineCertificates

/-! Explicit witnesses for all 54 actual small-hash constraint slices.
Every plan, wire layout, stage map and affine equation is instantiated
with a kernel-checked certificate. Only the ambient constant-wire
normalization is a premise. Generated by hash_assignment_completeness.py. -/

namespace MSP.Artifacts.HashAssignmentCompletenessSmall

open BetaGates SmallHashGates SmallHashGatesData HashAssignmentCompleteness
open HashAssignmentCompletenessData SmallHashGatesAffineCertificates
open AssignmentRecovery AssignmentRecoverySmallData

set_option maxRecDepth 131072
set_option maxHeartbeats 2000000

attribute [local irreducible] MSP.Poseidon.hash2 MSP.Poseidon.hash3

private theorem h2_reference (a b : F) : MSP.Poseidon.hash2 a b = H2 a b := by
  delta H2
  rfl

private theorem h3_reference (a b c : F) : MSP.Poseidon.hash3 a b c = H3 a b c := by
  delta H3
  rfl

structure Kit (g : Instance) where
  scheme : Scheme g.arity g.partialRounds
  affine : AffineCertificates g scheme
  signs : ∀ t, TripleSigns g t
  powers : PowerLayout g
  plan : Plan
  separate : WriteSeparation powers plan
  stages : StageMap g
  recovery : RecoveryCorrect g plan

def kit0 : Kit instance0 where
  scheme := scheme3
  affine := affine0
  signs := SmallHashGatesCertificates.signs ⟨0, by decide⟩
  powers := powers0
  plan := plan0
  separate := separate0
  stages := stages0
  recovery := AssignmentRecoverySmall.realizes ⟨0, by decide⟩

def kit1 : Kit instance1 where
  scheme := scheme3
  affine := affine1
  signs := SmallHashGatesCertificates.signs ⟨1, by decide⟩
  powers := powers1
  plan := plan1
  separate := separate1
  stages := stages1
  recovery := AssignmentRecoverySmall.realizes ⟨1, by decide⟩

def kit2 : Kit instance2 where
  scheme := scheme4
  affine := affine2
  signs := SmallHashGatesCertificates.signs ⟨2, by decide⟩
  powers := powers2
  plan := plan2
  separate := separate2
  stages := stages2
  recovery := AssignmentRecoverySmall.realizes ⟨2, by decide⟩

def kit3 : Kit instance3 where
  scheme := scheme3
  affine := affine3
  signs := SmallHashGatesCertificates.signs ⟨3, by decide⟩
  powers := powers3
  plan := plan3
  separate := separate3
  stages := stages3
  recovery := AssignmentRecoverySmall.realizes ⟨3, by decide⟩

def kit4 : Kit instance4 where
  scheme := scheme3
  affine := affine4
  signs := SmallHashGatesCertificates.signs ⟨4, by decide⟩
  powers := powers4
  plan := plan4
  separate := separate4
  stages := stages4
  recovery := AssignmentRecoverySmall.realizes ⟨4, by decide⟩

def kit5 : Kit instance5 where
  scheme := scheme3
  affine := affine5
  signs := SmallHashGatesCertificates.signs ⟨5, by decide⟩
  powers := powers5
  plan := plan5
  separate := separate5
  stages := stages5
  recovery := AssignmentRecoverySmall.realizes ⟨5, by decide⟩

def kit6 : Kit instance6 where
  scheme := scheme3
  affine := affine6
  signs := SmallHashGatesCertificates.signs ⟨6, by decide⟩
  powers := powers6
  plan := plan6
  separate := separate6
  stages := stages6
  recovery := AssignmentRecoverySmall.realizes ⟨6, by decide⟩

def kit7 : Kit instance7 where
  scheme := scheme3
  affine := affine7
  signs := SmallHashGatesCertificates.signs ⟨7, by decide⟩
  powers := powers7
  plan := plan7
  separate := separate7
  stages := stages7
  recovery := AssignmentRecoverySmall.realizes ⟨7, by decide⟩

def kit8 : Kit instance8 where
  scheme := scheme3
  affine := affine8
  signs := SmallHashGatesCertificates.signs ⟨8, by decide⟩
  powers := powers8
  plan := plan8
  separate := separate8
  stages := stages8
  recovery := AssignmentRecoverySmall.realizes ⟨8, by decide⟩

def kit9 : Kit instance9 where
  scheme := scheme3
  affine := affine9
  signs := SmallHashGatesCertificates.signs ⟨9, by decide⟩
  powers := powers9
  plan := plan9
  separate := separate9
  stages := stages9
  recovery := AssignmentRecoverySmall.realizes ⟨9, by decide⟩

def kit10 : Kit instance10 where
  scheme := scheme3
  affine := affine10
  signs := SmallHashGatesCertificates.signs ⟨10, by decide⟩
  powers := powers10
  plan := plan10
  separate := separate10
  stages := stages10
  recovery := AssignmentRecoverySmall.realizes ⟨10, by decide⟩

def kit11 : Kit instance11 where
  scheme := scheme3
  affine := affine11
  signs := SmallHashGatesCertificates.signs ⟨11, by decide⟩
  powers := powers11
  plan := plan11
  separate := separate11
  stages := stages11
  recovery := AssignmentRecoverySmall.realizes ⟨11, by decide⟩

def kit12 : Kit instance12 where
  scheme := scheme3
  affine := affine12
  signs := SmallHashGatesCertificates.signs ⟨12, by decide⟩
  powers := powers12
  plan := plan12
  separate := separate12
  stages := stages12
  recovery := AssignmentRecoverySmall.realizes ⟨12, by decide⟩

def kit13 : Kit instance13 where
  scheme := scheme3
  affine := affine13
  signs := SmallHashGatesCertificates.signs ⟨13, by decide⟩
  powers := powers13
  plan := plan13
  separate := separate13
  stages := stages13
  recovery := AssignmentRecoverySmall.realizes ⟨13, by decide⟩

def kit14 : Kit instance14 where
  scheme := scheme3
  affine := affine14
  signs := SmallHashGatesCertificates.signs ⟨14, by decide⟩
  powers := powers14
  plan := plan14
  separate := separate14
  stages := stages14
  recovery := AssignmentRecoverySmall.realizes ⟨14, by decide⟩

def kit15 : Kit instance15 where
  scheme := scheme3
  affine := affine15
  signs := SmallHashGatesCertificates.signs ⟨15, by decide⟩
  powers := powers15
  plan := plan15
  separate := separate15
  stages := stages15
  recovery := AssignmentRecoverySmall.realizes ⟨15, by decide⟩

def kit16 : Kit instance16 where
  scheme := scheme3
  affine := affine16
  signs := SmallHashGatesCertificates.signs ⟨16, by decide⟩
  powers := powers16
  plan := plan16
  separate := separate16
  stages := stages16
  recovery := AssignmentRecoverySmall.realizes ⟨16, by decide⟩

def kit17 : Kit instance17 where
  scheme := scheme3
  affine := affine17
  signs := SmallHashGatesCertificates.signs ⟨17, by decide⟩
  powers := powers17
  plan := plan17
  separate := separate17
  stages := stages17
  recovery := AssignmentRecoverySmall.realizes ⟨17, by decide⟩

def kit18 : Kit instance18 where
  scheme := scheme3
  affine := affine18
  signs := SmallHashGatesCertificates.signs ⟨18, by decide⟩
  powers := powers18
  plan := plan18
  separate := separate18
  stages := stages18
  recovery := AssignmentRecoverySmall.realizes ⟨18, by decide⟩

def kit19 : Kit instance19 where
  scheme := scheme3
  affine := affine19
  signs := SmallHashGatesCertificates.signs ⟨19, by decide⟩
  powers := powers19
  plan := plan19
  separate := separate19
  stages := stages19
  recovery := AssignmentRecoverySmall.realizes ⟨19, by decide⟩

def kit20 : Kit instance20 where
  scheme := scheme3
  affine := affine20
  signs := SmallHashGatesCertificates.signs ⟨20, by decide⟩
  powers := powers20
  plan := plan20
  separate := separate20
  stages := stages20
  recovery := AssignmentRecoverySmall.realizes ⟨20, by decide⟩

def kit21 : Kit instance21 where
  scheme := scheme3
  affine := affine21
  signs := SmallHashGatesCertificates.signs ⟨21, by decide⟩
  powers := powers21
  plan := plan21
  separate := separate21
  stages := stages21
  recovery := AssignmentRecoverySmall.realizes ⟨21, by decide⟩

def kit22 : Kit instance22 where
  scheme := scheme3
  affine := affine22
  signs := SmallHashGatesCertificates.signs ⟨22, by decide⟩
  powers := powers22
  plan := plan22
  separate := separate22
  stages := stages22
  recovery := AssignmentRecoverySmall.realizes ⟨22, by decide⟩

def kit23 : Kit instance23 where
  scheme := scheme4
  affine := affine23
  signs := SmallHashGatesCertificates.signs ⟨23, by decide⟩
  powers := powers23
  plan := plan23
  separate := separate23
  stages := stages23
  recovery := AssignmentRecoverySmall.realizes ⟨23, by decide⟩

def kit24 : Kit instance24 where
  scheme := scheme3
  affine := affine24
  signs := SmallHashGatesCertificates.signs ⟨24, by decide⟩
  powers := powers24
  plan := plan24
  separate := separate24
  stages := stages24
  recovery := AssignmentRecoverySmall.realizes ⟨24, by decide⟩

def kit25 : Kit instance25 where
  scheme := scheme4
  affine := affine25
  signs := SmallHashGatesCertificates.signs ⟨25, by decide⟩
  powers := powers25
  plan := plan25
  separate := separate25
  stages := stages25
  recovery := AssignmentRecoverySmall.realizes ⟨25, by decide⟩

def kit26 : Kit instance26 where
  scheme := scheme3
  affine := affine26
  signs := SmallHashGatesCertificates.signs ⟨26, by decide⟩
  powers := powers26
  plan := plan26
  separate := separate26
  stages := stages26
  recovery := AssignmentRecoverySmall.realizes ⟨26, by decide⟩

def kit27 : Kit instance27 where
  scheme := scheme3
  affine := affine27
  signs := SmallHashGatesCertificates.signs ⟨27, by decide⟩
  powers := powers27
  plan := plan27
  separate := separate27
  stages := stages27
  recovery := AssignmentRecoverySmall.realizes ⟨27, by decide⟩

def kit28 : Kit instance28 where
  scheme := scheme4
  affine := affine28
  signs := SmallHashGatesCertificates.signs ⟨28, by decide⟩
  powers := powers28
  plan := plan28
  separate := separate28
  stages := stages28
  recovery := AssignmentRecoverySmall.realizes ⟨28, by decide⟩

def kit29 : Kit instance29 where
  scheme := scheme3
  affine := affine29
  signs := SmallHashGatesCertificates.signs ⟨29, by decide⟩
  powers := powers29
  plan := plan29
  separate := separate29
  stages := stages29
  recovery := AssignmentRecoverySmall.realizes ⟨29, by decide⟩

def kit30 : Kit instance30 where
  scheme := scheme3
  affine := affine30
  signs := SmallHashGatesCertificates.signs ⟨30, by decide⟩
  powers := powers30
  plan := plan30
  separate := separate30
  stages := stages30
  recovery := AssignmentRecoverySmall.realizes ⟨30, by decide⟩

def kit31 : Kit instance31 where
  scheme := scheme3
  affine := affine31
  signs := SmallHashGatesCertificates.signs ⟨31, by decide⟩
  powers := powers31
  plan := plan31
  separate := separate31
  stages := stages31
  recovery := AssignmentRecoverySmall.realizes ⟨31, by decide⟩

def kit32 : Kit instance32 where
  scheme := scheme3
  affine := affine32
  signs := SmallHashGatesCertificates.signs ⟨32, by decide⟩
  powers := powers32
  plan := plan32
  separate := separate32
  stages := stages32
  recovery := AssignmentRecoverySmall.realizes ⟨32, by decide⟩

def kit33 : Kit instance33 where
  scheme := scheme3
  affine := affine33
  signs := SmallHashGatesCertificates.signs ⟨33, by decide⟩
  powers := powers33
  plan := plan33
  separate := separate33
  stages := stages33
  recovery := AssignmentRecoverySmall.realizes ⟨33, by decide⟩

def kit34 : Kit instance34 where
  scheme := scheme3
  affine := affine34
  signs := SmallHashGatesCertificates.signs ⟨34, by decide⟩
  powers := powers34
  plan := plan34
  separate := separate34
  stages := stages34
  recovery := AssignmentRecoverySmall.realizes ⟨34, by decide⟩

def kit35 : Kit instance35 where
  scheme := scheme3
  affine := affine35
  signs := SmallHashGatesCertificates.signs ⟨35, by decide⟩
  powers := powers35
  plan := plan35
  separate := separate35
  stages := stages35
  recovery := AssignmentRecoverySmall.realizes ⟨35, by decide⟩

def kit36 : Kit instance36 where
  scheme := scheme3
  affine := affine36
  signs := SmallHashGatesCertificates.signs ⟨36, by decide⟩
  powers := powers36
  plan := plan36
  separate := separate36
  stages := stages36
  recovery := AssignmentRecoverySmall.realizes ⟨36, by decide⟩

def kit37 : Kit instance37 where
  scheme := scheme3
  affine := affine37
  signs := SmallHashGatesCertificates.signs ⟨37, by decide⟩
  powers := powers37
  plan := plan37
  separate := separate37
  stages := stages37
  recovery := AssignmentRecoverySmall.realizes ⟨37, by decide⟩

def kit38 : Kit instance38 where
  scheme := scheme3
  affine := affine38
  signs := SmallHashGatesCertificates.signs ⟨38, by decide⟩
  powers := powers38
  plan := plan38
  separate := separate38
  stages := stages38
  recovery := AssignmentRecoverySmall.realizes ⟨38, by decide⟩

def kit39 : Kit instance39 where
  scheme := scheme3
  affine := affine39
  signs := SmallHashGatesCertificates.signs ⟨39, by decide⟩
  powers := powers39
  plan := plan39
  separate := separate39
  stages := stages39
  recovery := AssignmentRecoverySmall.realizes ⟨39, by decide⟩

def kit40 : Kit instance40 where
  scheme := scheme3
  affine := affine40
  signs := SmallHashGatesCertificates.signs ⟨40, by decide⟩
  powers := powers40
  plan := plan40
  separate := separate40
  stages := stages40
  recovery := AssignmentRecoverySmall.realizes ⟨40, by decide⟩

def kit41 : Kit instance41 where
  scheme := scheme3
  affine := affine41
  signs := SmallHashGatesCertificates.signs ⟨41, by decide⟩
  powers := powers41
  plan := plan41
  separate := separate41
  stages := stages41
  recovery := AssignmentRecoverySmall.realizes ⟨41, by decide⟩

def kit42 : Kit instance42 where
  scheme := scheme3
  affine := affine42
  signs := SmallHashGatesCertificates.signs ⟨42, by decide⟩
  powers := powers42
  plan := plan42
  separate := separate42
  stages := stages42
  recovery := AssignmentRecoverySmall.realizes ⟨42, by decide⟩

def kit43 : Kit instance43 where
  scheme := scheme3
  affine := affine43
  signs := SmallHashGatesCertificates.signs ⟨43, by decide⟩
  powers := powers43
  plan := plan43
  separate := separate43
  stages := stages43
  recovery := AssignmentRecoverySmall.realizes ⟨43, by decide⟩

def kit44 : Kit instance44 where
  scheme := scheme3
  affine := affine44
  signs := SmallHashGatesCertificates.signs ⟨44, by decide⟩
  powers := powers44
  plan := plan44
  separate := separate44
  stages := stages44
  recovery := AssignmentRecoverySmall.realizes ⟨44, by decide⟩

def kit45 : Kit instance45 where
  scheme := scheme3
  affine := affine45
  signs := SmallHashGatesCertificates.signs ⟨45, by decide⟩
  powers := powers45
  plan := plan45
  separate := separate45
  stages := stages45
  recovery := AssignmentRecoverySmall.realizes ⟨45, by decide⟩

def kit46 : Kit instance46 where
  scheme := scheme3
  affine := affine46
  signs := SmallHashGatesCertificates.signs ⟨46, by decide⟩
  powers := powers46
  plan := plan46
  separate := separate46
  stages := stages46
  recovery := AssignmentRecoverySmall.realizes ⟨46, by decide⟩

def kit47 : Kit instance47 where
  scheme := scheme3
  affine := affine47
  signs := SmallHashGatesCertificates.signs ⟨47, by decide⟩
  powers := powers47
  plan := plan47
  separate := separate47
  stages := stages47
  recovery := AssignmentRecoverySmall.realizes ⟨47, by decide⟩

def kit48 : Kit instance48 where
  scheme := scheme3
  affine := affine48
  signs := SmallHashGatesCertificates.signs ⟨48, by decide⟩
  powers := powers48
  plan := plan48
  separate := separate48
  stages := stages48
  recovery := AssignmentRecoverySmall.realizes ⟨48, by decide⟩

def kit49 : Kit instance49 where
  scheme := scheme4
  affine := affine49
  signs := SmallHashGatesCertificates.signs ⟨49, by decide⟩
  powers := powers49
  plan := plan49
  separate := separate49
  stages := stages49
  recovery := AssignmentRecoverySmall.realizes ⟨49, by decide⟩

def kit50 : Kit instance50 where
  scheme := scheme3
  affine := affine50
  signs := SmallHashGatesCertificates.signs ⟨50, by decide⟩
  powers := powers50
  plan := plan50
  separate := separate50
  stages := stages50
  recovery := AssignmentRecoverySmall.realizes ⟨50, by decide⟩

def kit51 : Kit instance51 where
  scheme := scheme4
  affine := affine51
  signs := SmallHashGatesCertificates.signs ⟨51, by decide⟩
  powers := powers51
  plan := plan51
  separate := separate51
  stages := stages51
  recovery := AssignmentRecoverySmall.realizes ⟨51, by decide⟩

def kit52 : Kit instance52 where
  scheme := scheme4
  affine := affine52
  signs := SmallHashGatesCertificates.signs ⟨52, by decide⟩
  powers := powers52
  plan := plan52
  separate := separate52
  stages := stages52
  recovery := AssignmentRecoverySmall.realizes ⟨52, by decide⟩

def kit53 : Kit instance53 where
  scheme := scheme4
  affine := affine53
  signs := SmallHashGatesCertificates.signs ⟨53, by decide⟩
  powers := powers53
  plan := plan53
  separate := separate53
  stages := stages53
  recovery := AssignmentRecoverySmall.realizes ⟨53, by decide⟩

def kit (i : Fin 54) : Kit (gate i) :=
  match i with
  | ⟨0, _⟩ => kit0
  | ⟨1, _⟩ => kit1
  | ⟨2, _⟩ => kit2
  | ⟨3, _⟩ => kit3
  | ⟨4, _⟩ => kit4
  | ⟨5, _⟩ => kit5
  | ⟨6, _⟩ => kit6
  | ⟨7, _⟩ => kit7
  | ⟨8, _⟩ => kit8
  | ⟨9, _⟩ => kit9
  | ⟨10, _⟩ => kit10
  | ⟨11, _⟩ => kit11
  | ⟨12, _⟩ => kit12
  | ⟨13, _⟩ => kit13
  | ⟨14, _⟩ => kit14
  | ⟨15, _⟩ => kit15
  | ⟨16, _⟩ => kit16
  | ⟨17, _⟩ => kit17
  | ⟨18, _⟩ => kit18
  | ⟨19, _⟩ => kit19
  | ⟨20, _⟩ => kit20
  | ⟨21, _⟩ => kit21
  | ⟨22, _⟩ => kit22
  | ⟨23, _⟩ => kit23
  | ⟨24, _⟩ => kit24
  | ⟨25, _⟩ => kit25
  | ⟨26, _⟩ => kit26
  | ⟨27, _⟩ => kit27
  | ⟨28, _⟩ => kit28
  | ⟨29, _⟩ => kit29
  | ⟨30, _⟩ => kit30
  | ⟨31, _⟩ => kit31
  | ⟨32, _⟩ => kit32
  | ⟨33, _⟩ => kit33
  | ⟨34, _⟩ => kit34
  | ⟨35, _⟩ => kit35
  | ⟨36, _⟩ => kit36
  | ⟨37, _⟩ => kit37
  | ⟨38, _⟩ => kit38
  | ⟨39, _⟩ => kit39
  | ⟨40, _⟩ => kit40
  | ⟨41, _⟩ => kit41
  | ⟨42, _⟩ => kit42
  | ⟨43, _⟩ => kit43
  | ⟨44, _⟩ => kit44
  | ⟨45, _⟩ => kit45
  | ⟨46, _⟩ => kit46
  | ⟨47, _⟩ => kit47
  | ⟨48, _⟩ => kit48
  | ⟨49, _⟩ => kit49
  | ⟨50, _⟩ => kit50
  | ⟨51, _⟩ => kit51
  | ⟨52, _⟩ => kit52
  | ⟨53, _⟩ => kit53
  | ⟨n + 54, h⟩ => False.elim (by omega)

noncomputable def assignment (i : Fin 54) (ambient : Assignment) : Assignment :=
  buildAssignment (kit i).scheme (kit i).powers (kit i).plan (kit i).stages ambient

theorem zero (i : Fin 54) (ambient : Assignment) :
    assignment i ambient 0 = ambient 0 :=
  buildAssignment_zero _ _ _ _ _

theorem inputs (i : Fin 54) (ambient : Assignment) (j : Fin (gate i).arity) :
    eval ((gate i).inputForms j) (assignment i ambient) =
      eval ((gate i).inputForms j) ambient :=
  buildAssignment_inputs _ _ _ (kit i).separate _ _ _

theorem complete (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :
    (∀ c ∈ (gate i).constraints, c.Holds (assignment i ambient)) ∧
    eval (gate i).outputForm (assignment i ambient) =
      (kit i).scheme.hash (ambientInputs (gate i) ambient) :=
  buildAssignment_complete _ (kit i).affine (kit i).signs _ _ (kit i).separate
    _ (kit i).recovery ambient hz

theorem assignment_hash (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :
    eval (gate i).outputForm (assignment i ambient) =
      (kit i).scheme.hash (ambientInputs (gate i) (assignment i ambient)) := by
  have hi : ambientInputs (gate i) (assignment i ambient) =
      ambientInputs (gate i) ambient := funext (inputs i ambient)
  rw [hi]
  exact (complete i ambient hz).2

/-- The constructed witness has the exact reference H2/H3 interface. -/
theorem hash_binding (i : Fin 54) (ambient : Assignment) (hz : ambient 0 = 1) :
    HashBinding (assignment i ambient) i := by
  fin_cases i
  · have hh := assignment_hash ⟨0, by decide⟩ ambient hz
    rw [show (kit ⟨0, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance0.outputForm (assignment ⟨0, by decide⟩ ambient) = H2 (eval (inputAt instance0 0) (assignment ⟨0, by decide⟩ ambient)) (eval (inputAt instance0 1) (assignment ⟨0, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨1, by decide⟩ ambient hz
    rw [show (kit ⟨1, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance1.outputForm (assignment ⟨1, by decide⟩ ambient) = H2 (eval (inputAt instance1 0) (assignment ⟨1, by decide⟩ ambient)) (eval (inputAt instance1 1) (assignment ⟨1, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨2, by decide⟩ ambient hz
    rw [show (kit ⟨2, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance2.outputForm (assignment ⟨2, by decide⟩ ambient) = H3 (eval (inputAt instance2 0) (assignment ⟨2, by decide⟩ ambient)) (eval (inputAt instance2 1) (assignment ⟨2, by decide⟩ ambient)) (eval (inputAt instance2 2) (assignment ⟨2, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨3, by decide⟩ ambient hz
    rw [show (kit ⟨3, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance3.outputForm (assignment ⟨3, by decide⟩ ambient) = H2 (eval (inputAt instance3 0) (assignment ⟨3, by decide⟩ ambient)) (eval (inputAt instance3 1) (assignment ⟨3, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨4, by decide⟩ ambient hz
    rw [show (kit ⟨4, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance4.outputForm (assignment ⟨4, by decide⟩ ambient) = H2 (eval (inputAt instance4 0) (assignment ⟨4, by decide⟩ ambient)) (eval (inputAt instance4 1) (assignment ⟨4, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨5, by decide⟩ ambient hz
    rw [show (kit ⟨5, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance5.outputForm (assignment ⟨5, by decide⟩ ambient) = H2 (eval (inputAt instance5 0) (assignment ⟨5, by decide⟩ ambient)) (eval (inputAt instance5 1) (assignment ⟨5, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨6, by decide⟩ ambient hz
    rw [show (kit ⟨6, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance6.outputForm (assignment ⟨6, by decide⟩ ambient) = H2 (eval (inputAt instance6 0) (assignment ⟨6, by decide⟩ ambient)) (eval (inputAt instance6 1) (assignment ⟨6, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨7, by decide⟩ ambient hz
    rw [show (kit ⟨7, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance7.outputForm (assignment ⟨7, by decide⟩ ambient) = H2 (eval (inputAt instance7 0) (assignment ⟨7, by decide⟩ ambient)) (eval (inputAt instance7 1) (assignment ⟨7, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨8, by decide⟩ ambient hz
    rw [show (kit ⟨8, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance8.outputForm (assignment ⟨8, by decide⟩ ambient) = H2 (eval (inputAt instance8 0) (assignment ⟨8, by decide⟩ ambient)) (eval (inputAt instance8 1) (assignment ⟨8, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨9, by decide⟩ ambient hz
    rw [show (kit ⟨9, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance9.outputForm (assignment ⟨9, by decide⟩ ambient) = H2 (eval (inputAt instance9 0) (assignment ⟨9, by decide⟩ ambient)) (eval (inputAt instance9 1) (assignment ⟨9, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨10, by decide⟩ ambient hz
    rw [show (kit ⟨10, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance10.outputForm (assignment ⟨10, by decide⟩ ambient) = H2 (eval (inputAt instance10 0) (assignment ⟨10, by decide⟩ ambient)) (eval (inputAt instance10 1) (assignment ⟨10, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨11, by decide⟩ ambient hz
    rw [show (kit ⟨11, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance11.outputForm (assignment ⟨11, by decide⟩ ambient) = H2 (eval (inputAt instance11 0) (assignment ⟨11, by decide⟩ ambient)) (eval (inputAt instance11 1) (assignment ⟨11, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨12, by decide⟩ ambient hz
    rw [show (kit ⟨12, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance12.outputForm (assignment ⟨12, by decide⟩ ambient) = H2 (eval (inputAt instance12 0) (assignment ⟨12, by decide⟩ ambient)) (eval (inputAt instance12 1) (assignment ⟨12, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨13, by decide⟩ ambient hz
    rw [show (kit ⟨13, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance13.outputForm (assignment ⟨13, by decide⟩ ambient) = H2 (eval (inputAt instance13 0) (assignment ⟨13, by decide⟩ ambient)) (eval (inputAt instance13 1) (assignment ⟨13, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨14, by decide⟩ ambient hz
    rw [show (kit ⟨14, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance14.outputForm (assignment ⟨14, by decide⟩ ambient) = H2 (eval (inputAt instance14 0) (assignment ⟨14, by decide⟩ ambient)) (eval (inputAt instance14 1) (assignment ⟨14, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨15, by decide⟩ ambient hz
    rw [show (kit ⟨15, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance15.outputForm (assignment ⟨15, by decide⟩ ambient) = H2 (eval (inputAt instance15 0) (assignment ⟨15, by decide⟩ ambient)) (eval (inputAt instance15 1) (assignment ⟨15, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨16, by decide⟩ ambient hz
    rw [show (kit ⟨16, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance16.outputForm (assignment ⟨16, by decide⟩ ambient) = H2 (eval (inputAt instance16 0) (assignment ⟨16, by decide⟩ ambient)) (eval (inputAt instance16 1) (assignment ⟨16, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨17, by decide⟩ ambient hz
    rw [show (kit ⟨17, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance17.outputForm (assignment ⟨17, by decide⟩ ambient) = H2 (eval (inputAt instance17 0) (assignment ⟨17, by decide⟩ ambient)) (eval (inputAt instance17 1) (assignment ⟨17, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨18, by decide⟩ ambient hz
    rw [show (kit ⟨18, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance18.outputForm (assignment ⟨18, by decide⟩ ambient) = H2 (eval (inputAt instance18 0) (assignment ⟨18, by decide⟩ ambient)) (eval (inputAt instance18 1) (assignment ⟨18, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨19, by decide⟩ ambient hz
    rw [show (kit ⟨19, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance19.outputForm (assignment ⟨19, by decide⟩ ambient) = H2 (eval (inputAt instance19 0) (assignment ⟨19, by decide⟩ ambient)) (eval (inputAt instance19 1) (assignment ⟨19, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨20, by decide⟩ ambient hz
    rw [show (kit ⟨20, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance20.outputForm (assignment ⟨20, by decide⟩ ambient) = H2 (eval (inputAt instance20 0) (assignment ⟨20, by decide⟩ ambient)) (eval (inputAt instance20 1) (assignment ⟨20, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨21, by decide⟩ ambient hz
    rw [show (kit ⟨21, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance21.outputForm (assignment ⟨21, by decide⟩ ambient) = H2 (eval (inputAt instance21 0) (assignment ⟨21, by decide⟩ ambient)) (eval (inputAt instance21 1) (assignment ⟨21, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨22, by decide⟩ ambient hz
    rw [show (kit ⟨22, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance22.outputForm (assignment ⟨22, by decide⟩ ambient) = H2 (eval (inputAt instance22 0) (assignment ⟨22, by decide⟩ ambient)) (eval (inputAt instance22 1) (assignment ⟨22, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨23, by decide⟩ ambient hz
    rw [show (kit ⟨23, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance23.outputForm (assignment ⟨23, by decide⟩ ambient) = H3 (eval (inputAt instance23 0) (assignment ⟨23, by decide⟩ ambient)) (eval (inputAt instance23 1) (assignment ⟨23, by decide⟩ ambient)) (eval (inputAt instance23 2) (assignment ⟨23, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨24, by decide⟩ ambient hz
    rw [show (kit ⟨24, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance24.outputForm (assignment ⟨24, by decide⟩ ambient) = H2 (eval (inputAt instance24 0) (assignment ⟨24, by decide⟩ ambient)) (eval (inputAt instance24 1) (assignment ⟨24, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨25, by decide⟩ ambient hz
    rw [show (kit ⟨25, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance25.outputForm (assignment ⟨25, by decide⟩ ambient) = H3 (eval (inputAt instance25 0) (assignment ⟨25, by decide⟩ ambient)) (eval (inputAt instance25 1) (assignment ⟨25, by decide⟩ ambient)) (eval (inputAt instance25 2) (assignment ⟨25, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨26, by decide⟩ ambient hz
    rw [show (kit ⟨26, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance26.outputForm (assignment ⟨26, by decide⟩ ambient) = H2 (eval (inputAt instance26 0) (assignment ⟨26, by decide⟩ ambient)) (eval (inputAt instance26 1) (assignment ⟨26, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨27, by decide⟩ ambient hz
    rw [show (kit ⟨27, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance27.outputForm (assignment ⟨27, by decide⟩ ambient) = H2 (eval (inputAt instance27 0) (assignment ⟨27, by decide⟩ ambient)) (eval (inputAt instance27 1) (assignment ⟨27, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨28, by decide⟩ ambient hz
    rw [show (kit ⟨28, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance28.outputForm (assignment ⟨28, by decide⟩ ambient) = H3 (eval (inputAt instance28 0) (assignment ⟨28, by decide⟩ ambient)) (eval (inputAt instance28 1) (assignment ⟨28, by decide⟩ ambient)) (eval (inputAt instance28 2) (assignment ⟨28, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨29, by decide⟩ ambient hz
    rw [show (kit ⟨29, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance29.outputForm (assignment ⟨29, by decide⟩ ambient) = H2 (eval (inputAt instance29 0) (assignment ⟨29, by decide⟩ ambient)) (eval (inputAt instance29 1) (assignment ⟨29, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨30, by decide⟩ ambient hz
    rw [show (kit ⟨30, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance30.outputForm (assignment ⟨30, by decide⟩ ambient) = H2 (eval (inputAt instance30 0) (assignment ⟨30, by decide⟩ ambient)) (eval (inputAt instance30 1) (assignment ⟨30, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨31, by decide⟩ ambient hz
    rw [show (kit ⟨31, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance31.outputForm (assignment ⟨31, by decide⟩ ambient) = H2 (eval (inputAt instance31 0) (assignment ⟨31, by decide⟩ ambient)) (eval (inputAt instance31 1) (assignment ⟨31, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨32, by decide⟩ ambient hz
    rw [show (kit ⟨32, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance32.outputForm (assignment ⟨32, by decide⟩ ambient) = H2 (eval (inputAt instance32 0) (assignment ⟨32, by decide⟩ ambient)) (eval (inputAt instance32 1) (assignment ⟨32, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨33, by decide⟩ ambient hz
    rw [show (kit ⟨33, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance33.outputForm (assignment ⟨33, by decide⟩ ambient) = H2 (eval (inputAt instance33 0) (assignment ⟨33, by decide⟩ ambient)) (eval (inputAt instance33 1) (assignment ⟨33, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨34, by decide⟩ ambient hz
    rw [show (kit ⟨34, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance34.outputForm (assignment ⟨34, by decide⟩ ambient) = H2 (eval (inputAt instance34 0) (assignment ⟨34, by decide⟩ ambient)) (eval (inputAt instance34 1) (assignment ⟨34, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨35, by decide⟩ ambient hz
    rw [show (kit ⟨35, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance35.outputForm (assignment ⟨35, by decide⟩ ambient) = H2 (eval (inputAt instance35 0) (assignment ⟨35, by decide⟩ ambient)) (eval (inputAt instance35 1) (assignment ⟨35, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨36, by decide⟩ ambient hz
    rw [show (kit ⟨36, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance36.outputForm (assignment ⟨36, by decide⟩ ambient) = H2 (eval (inputAt instance36 0) (assignment ⟨36, by decide⟩ ambient)) (eval (inputAt instance36 1) (assignment ⟨36, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨37, by decide⟩ ambient hz
    rw [show (kit ⟨37, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance37.outputForm (assignment ⟨37, by decide⟩ ambient) = H2 (eval (inputAt instance37 0) (assignment ⟨37, by decide⟩ ambient)) (eval (inputAt instance37 1) (assignment ⟨37, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨38, by decide⟩ ambient hz
    rw [show (kit ⟨38, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance38.outputForm (assignment ⟨38, by decide⟩ ambient) = H2 (eval (inputAt instance38 0) (assignment ⟨38, by decide⟩ ambient)) (eval (inputAt instance38 1) (assignment ⟨38, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨39, by decide⟩ ambient hz
    rw [show (kit ⟨39, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance39.outputForm (assignment ⟨39, by decide⟩ ambient) = H2 (eval (inputAt instance39 0) (assignment ⟨39, by decide⟩ ambient)) (eval (inputAt instance39 1) (assignment ⟨39, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨40, by decide⟩ ambient hz
    rw [show (kit ⟨40, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance40.outputForm (assignment ⟨40, by decide⟩ ambient) = H2 (eval (inputAt instance40 0) (assignment ⟨40, by decide⟩ ambient)) (eval (inputAt instance40 1) (assignment ⟨40, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨41, by decide⟩ ambient hz
    rw [show (kit ⟨41, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance41.outputForm (assignment ⟨41, by decide⟩ ambient) = H2 (eval (inputAt instance41 0) (assignment ⟨41, by decide⟩ ambient)) (eval (inputAt instance41 1) (assignment ⟨41, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨42, by decide⟩ ambient hz
    rw [show (kit ⟨42, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance42.outputForm (assignment ⟨42, by decide⟩ ambient) = H2 (eval (inputAt instance42 0) (assignment ⟨42, by decide⟩ ambient)) (eval (inputAt instance42 1) (assignment ⟨42, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨43, by decide⟩ ambient hz
    rw [show (kit ⟨43, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance43.outputForm (assignment ⟨43, by decide⟩ ambient) = H2 (eval (inputAt instance43 0) (assignment ⟨43, by decide⟩ ambient)) (eval (inputAt instance43 1) (assignment ⟨43, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨44, by decide⟩ ambient hz
    rw [show (kit ⟨44, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance44.outputForm (assignment ⟨44, by decide⟩ ambient) = H2 (eval (inputAt instance44 0) (assignment ⟨44, by decide⟩ ambient)) (eval (inputAt instance44 1) (assignment ⟨44, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨45, by decide⟩ ambient hz
    rw [show (kit ⟨45, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance45.outputForm (assignment ⟨45, by decide⟩ ambient) = H2 (eval (inputAt instance45 0) (assignment ⟨45, by decide⟩ ambient)) (eval (inputAt instance45 1) (assignment ⟨45, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨46, by decide⟩ ambient hz
    rw [show (kit ⟨46, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance46.outputForm (assignment ⟨46, by decide⟩ ambient) = H2 (eval (inputAt instance46 0) (assignment ⟨46, by decide⟩ ambient)) (eval (inputAt instance46 1) (assignment ⟨46, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨47, by decide⟩ ambient hz
    rw [show (kit ⟨47, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance47.outputForm (assignment ⟨47, by decide⟩ ambient) = H2 (eval (inputAt instance47 0) (assignment ⟨47, by decide⟩ ambient)) (eval (inputAt instance47 1) (assignment ⟨47, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨48, by decide⟩ ambient hz
    rw [show (kit ⟨48, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance48.outputForm (assignment ⟨48, by decide⟩ ambient) = H2 (eval (inputAt instance48 0) (assignment ⟨48, by decide⟩ ambient)) (eval (inputAt instance48 1) (assignment ⟨48, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨49, by decide⟩ ambient hz
    rw [show (kit ⟨49, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance49.outputForm (assignment ⟨49, by decide⟩ ambient) = H3 (eval (inputAt instance49 0) (assignment ⟨49, by decide⟩ ambient)) (eval (inputAt instance49 1) (assignment ⟨49, by decide⟩ ambient)) (eval (inputAt instance49 2) (assignment ⟨49, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨50, by decide⟩ ambient hz
    rw [show (kit ⟨50, by decide⟩).scheme = scheme3 from rfl] at hh
    erw [scheme3_hash, MSP.Poseidon.Optimized3.hash2_eq_reference] at hh
    change eval instance50.outputForm (assignment ⟨50, by decide⟩ ambient) = H2 (eval (inputAt instance50 0) (assignment ⟨50, by decide⟩ ambient)) (eval (inputAt instance50 1) (assignment ⟨50, by decide⟩ ambient))
    exact hh.trans (h2_reference _ _)
  · have hh := assignment_hash ⟨51, by decide⟩ ambient hz
    rw [show (kit ⟨51, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance51.outputForm (assignment ⟨51, by decide⟩ ambient) = H3 (eval (inputAt instance51 0) (assignment ⟨51, by decide⟩ ambient)) (eval (inputAt instance51 1) (assignment ⟨51, by decide⟩ ambient)) (eval (inputAt instance51 2) (assignment ⟨51, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨52, by decide⟩ ambient hz
    rw [show (kit ⟨52, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance52.outputForm (assignment ⟨52, by decide⟩ ambient) = H3 (eval (inputAt instance52 0) (assignment ⟨52, by decide⟩ ambient)) (eval (inputAt instance52 1) (assignment ⟨52, by decide⟩ ambient)) (eval (inputAt instance52 2) (assignment ⟨52, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)
  · have hh := assignment_hash ⟨53, by decide⟩ ambient hz
    rw [show (kit ⟨53, by decide⟩).scheme = scheme4 from rfl] at hh
    erw [scheme4_hash, MSP.Poseidon.Optimized4.hash3_eq_reference] at hh
    change eval instance53.outputForm (assignment ⟨53, by decide⟩ ambient) = H3 (eval (inputAt instance53 0) (assignment ⟨53, by decide⟩ ambient)) (eval (inputAt instance53 1) (assignment ⟨53, by decide⟩ ambient)) (eval (inputAt instance53 2) (assignment ⟨53, by decide⟩ ambient))
    exact hh.trans (h3_reference _ _ _)

theorem preserves (i : Fin 54) (ambient : Assignment) (wire : ℕ)
    (hrecovery : wire ∉ (kit i).plan.written)
    (hpowers : ∀ k, (kit i).powers.wire k ≠ wire) :
    assignment i ambient wire = ambient wire :=
  buildAssignment_preserves _ _ _ _ _ _ hrecovery hpowers

end MSP.Artifacts.HashAssignmentCompletenessSmall
